- .storybook/Box.js
- .storybook/Text.js
- .storybook/config.js
- package.json
- src/Box.js
- src/Text.js
> Storybook info addon

- .gitignore
- .travis.yml
- package.json
> Add travis deploy config

- .storybook/Flex.js
- README.md
- src/Flex.js
- src/__tests__/Flex.js
- src/__tests__/__snapshots__/Flex.js.snap
- src/index.js
> Flex component

- .storybook/Image.js
- README.md
- src/Image.js
- src/__tests__/Image.js
- src/__tests__/__snapshots__/Image.js.snap
- src/index.js
* Adds Image component.
Fixes #21
> Adds Image component

- .storybook/Layouts.js
- docs/Layout.md
Adds some example stories and a doc on how to use the Box and Flex components for different layouts
> Layout examples docs

- src/Icon.js
- src/__tests__/__snapshots__/Flex.js.snap
This PR allow to pass the size as a string in the Icon component
> fix(proptype): added string in the icon size proptype

- .storybook/Button.js
- src/Button.js
Added docks for story book, get theme from props now.
> feat(87) added docks for story book, get theme from props now

- .storybook/Text.js
- docs/Text.md
- src/Text.js
Enable strikethough.  Useful for price striethroughs.
> feat(text-strikethrough): enable strikethrough

- README.md
- docs/Card.md
- src/Card.js
Small change refactoring `function` to `const/arrow function` commented by @hakimelek after this PR merge: https://github.com/pricelinelabs/design-system/pull/100
> refactor card component with arrow fn

- package.json
Prettier is a code formatter that helps negate the need for listing and making sure your code follows a particular style. It runs as a precommit hook and formats code to a consistent style
See https://github.com/prettier/prettier for more about how it works
> Use prettier for code formatting

- icons/star-half.svg
- icons/star.svg
- src/__tests__/__snapshots__/Icon.js.snap
> added half-star, updated star img

- README.md
- src/Banner.js
add title to and edit margin of close button
> Banner close button updates

- .storybook/Icon.js
- .storybook/IconButton.js
minor storybook improvments for icon related stories
> feat(icon-storybook): show all new icons

- src/Hug.js
- src/__tests__/__snapshots__/Hug.js.snap
> feat(hug-border-removal): no borders allowed on child EVER

- .storybook/InputField.js
- docs/InputField.md
- docs/README.md
- src/Input.js
- src/InputField.js
- src/Label.js
- src/__tests__/InputField.js
- src/__tests__/__snapshots__/Input.js.snap
- src/__tests__/__snapshots__/InputField.js.snap
- src/__tests__/__snapshots__/Label.js.snap
This PR is to add support for a compound version of the InputField component. What this allows is the consumer will have more flexibility in the appearance of the component. 
Please view https://github.com/pricelinelabs/design-system/blob/feature/compound-input-components/docs/InputField.md for more information.
feat(InputField): replace old InputField with backwards compatibile compound component
feat(input-field): add unit tests for InputField component
docs(input-field): add documentation for InputField component
> feat(InputField): add InputField component

- .storybook/Text.js
- docs/Text.md
- src/Text.js
- src/__tests__/Text.js
- src/__tests__/__snapshots__/Text.js.snap
Came across a use for this in the SEO project. It's a simple update so I figured I'd just open a PR and see what you folks think :)
> feat(Text): allow for the text component to have an italic option

- icons/new/minus.svg
- icons/new/plus.svg
- src/__tests__/__snapshots__/Icon.js.snap
Wanted to add `plus` and `minus` icons to the set. We currently have plus & minus within a radio and box but not standalone.
> Created `plus` and `minus` icons

- src/InputField.js
Most of the changes here is just it being prettified. The only real change I made was a null check to the complex 'children' propType.
> bug(InputField): Fix small prop type validation error

- src/Hug.js
- src/__tests__/__snapshots__/Hug.js.snap
for issue [#175](https://github.com/pricelinelabs/design-system/issues/175)
> Hug: use Text component to have 100% width in the hug

- .storybook/Colors.js
- .storybook/Layouts.js
- .storybook/Link.js
- src/Badge.js
- src/__tests__/Badge.js
- src/__tests__/theme.js
- src/theme.js
If you would like to use something like `blue0` now. You will see something like this in your console.
Also, added some flags in the storybook
Thanks @747823 for the help :)
> Add numbered colors deprecation warning

- .storybook/Radio.js
- src/Radio.js
- src/__tests__/__snapshots__/Radio.js.snap
> fixed Radio alignment

- .storybook/Card.js
- src/Card.js
- src/Tooltip.js
- src/__tests__/Card.js
- src/__tests__/__snapshots__/Card.js.snap
- src/__tests__/__snapshots__/Tooltip.js.snap
- src/__tests__/__snapshots__/theme.js.snap
- src/theme.js
> Created new boxShadow values

- src/Icon.js
- src/__tests__/__snapshots__/Banner.js.snap
- src/__tests__/__snapshots__/Select.js.snap
Same as #199, with fixing tests and adding the color proptype.
> fix(Icon): removed space props from svg element

- icons/new/freeCancellation.svg
- icons/new/menu.svg
- src/__tests__/__snapshots__/Icon.js.snap
> Added 'menu' and 'freeCancellation' icons

- package.json
* Add styled-components to peer dependency.
* Loosen styled-components version to ^2.0.0 and ^3.0.0.
> Add styled-components to peer dependency

- .storybook/Flag.js
- src/Flag.js
- src/__tests__/__snapshots__/Flag.js.snap
- src/__tests__/__snapshots__/InputGroup.js.snap
Making `Flag` component responsive
> Responsive flag

- src/RatingBadge.js
- src/__tests__/__snapshots__/RatingBadge.js.snap
Per Wes design request, reducing the ratingBadge borderRadius from 2 to 1
> update ratingBadge borderRadius

- docs/src/Color.js
I added the missing colors from the new docs site including Black, White, Text, and BorderGray.
> Added missing colors to docs

- .travis.yml
@tmeasday does this sound correct?
> Change Travis chromatic step to push event

- src/InputField.js
- src/__tests__/__snapshots__/InputField.js.snap
Adds `pointer-events: none` to the InputField's Box components to allow clicking on icons to focus the Input
> Make InputField icons clickable

- src/Checkbox.js
- src/Flag.js
- src/Radio.js
Added default theme props to Radio component to avoid undefined props.
> Add defaultProps to Radio

- src/theme.js
In reference to #228 - adds standard easing curves for animation. 
easeInOut - base easing for core animations
easeOut - used for elements entering frame
easeIn - used for elements exiting frame
> Add easing curves

- .npmignore
> ignore icons folder for npm

- icons/new/emoticon.svg
- icons/new/golf.svg
- icons/new/localBar.svg
- icons/new/rowing.svg
- src/__tests__/__snapshots__/Icon.js.snap
Added emoticon, golf, localBar, and rowing icons.
> Added emoticon, golf, localBar, and rowing icons.

- src/OutlineButton.js
- src/__tests__/OutlineButton.js
- src/__tests__/__snapshots__/InputField.js.snap
- src/__tests__/__snapshots__/OutlineButton.js.snap
Fixes #309 — not sure why InputField snapshots were updated but tests wouldn't pass without it.
> Removed border from OutlineButton in favor of inset box-shadow

- docs/Heading.md
- docs/Text.md
Please review updates to code snippets (this was mostly for an example for the design team 😄)
> Fixed docs errors

- .storybook/FormField.js
- src/FormField.js
- src/__tests__/InputField.js
- src/__tests__/__snapshots__/InputField.js.snap
When using `Form Field`, there are some unwanted style issues if we pass a valid `hidden` prop to the Label component:
```<Label hidden>Pick-up Location</Label>```
Example:
This PR should resolve this:
Note: If `alwaysShowLabel` is passed as a prop to `Form Field`, Label should not have a `hidden` prop because that makes no sense.
> add logic to form field when Label has hidden prop

- .storybook/Absolute.js
- docs/Absolute.md
- docs/src/App.js
- src/Absolute.js
- src/__tests__/Absolute.js
- src/__tests__/__snapshots__/Absolute.js.snap
- src/__tests__/__snapshots__/InputGroup.js.snap
- src/index.js
> add absolute component

- .storybook/ToggleBadge.js
- docs/ToggleBadge.md
- src/ToggleBadge.js
- src/__tests__/__snapshots__/ToggleBadge.js.snap
unselected badge has transparent background
> for unselected badge the color is now transparent

- src/theme.js
> Remove numbered colors warnings

- .storybook/IconButton.js
- src/IconButton.js
- src/__tests__/__snapshots__/CloseButton.js.snap
- src/__tests__/__snapshots__/IconButton.js.snap
> Adjust IconButton styles

- docs/src/navigation.js
The last PR has a typo in URL, sorry about that
> Fix a typo in URL

- src/Card.js
- src/__tests__/Card.js
- src/__tests__/__snapshots__/Card.js.snap
https://github.com/pricelinelabs/design-system/issues/383
> Card should accept borderWidth={0}

- src/Text.js
- src/__tests__/__snapshots__/Heading.js.snap
- src/__tests__/__snapshots__/Text.js.snap
> fixes #351 caps Text to use caps letterSpacing

- CHANGELOG.md
- docs/pages/Hide.md
- packages/core/src/Hide.js
- packages/core/storybook/Hide.js
- packages/core/test/Hide.js
- packages/core/test/__snapshots__/Hide.js.snap
Add print prop to Hide component
Add test case, story, and doc for Hide in print
print prop will set display: none for @media print
> feat(hide-for-print): Add ability to hide for print media

- packages/core/src/theme.js
- packages/core/test/__snapshots__/theme.js.snap
* adding yellow and lightYellow colors to the theme
> chore(colors): correct yellow and lightYellow hexcodes and add to theme

- packages/modal/package.json
made a change in modal's package.json, change `main` and add `module`
> fix modal's main and module in package.json

- docs/package-lock.json
- docs/package.json
- docs/src/components.js
fixes #474 Add Slider to Docs Site 
Before: 
After:  💯
> feat: Add Slider to Docs Site

- packages/core/src/FormField.js
- packages/core/storybook/FormField.js
> Fix padding around input when FormField doesn't have label

- docs/pages/Stamp.md
- packages/core/src/Stamp.js
- packages/core/storybook/Stamp.js
- packages/core/test/Stamp.js
- packages/core/test/__snapshots__/Stamp.js.snap
> Add borderColor prop to Stamp

- CONTRIBUTING.md
Added documentation about publishing based on personal experience
> feat(publishing): add documentation about publishing

- package-lock.json
- packages/core/src/Label.js
- packages/core/storybook/Label.js
- packages/core/test/Label.js
- packages/core/test/__snapshots__/Label.js.snap
> Add width to label

- packages/icons/package-lock.json
- packages/icons/package.json
- packages/slider/test/__snapshots__/index.js.snap
Updating icons to version `2.1.0`, will create a release once merged in.
> Icons version 2.1.0

- packages/core/src/IconButton.js
- packages/core/src/utils.js
- Fixing an issue with camel case palette colors not applying
- Adding a component styles hook to IconButton
> Fix: fixing palette colors with camel case names

- packages/core/package-lock.json
- packages/core/package.json
updating core to 2.4.0, will tag and publish after merge.
> Release: Core 2.4.0

- package-lock.json
- packages/popover/src/Overlay.js
- packages/popover/src/Popover.js
- packages/popover/src/PopoverContent.js
- packages/popover/src/helpers/defaultModifiers.js
- packages/popover/storybook/PopOver.js
- packages/popover/test/Overlay.js
- packages/popover/test/Popover.js
- packages/popover/test/__snapshots__/Overlay.js.snap
- Fix automatic scroll when user opens popover
- A11y updates
- Fix issue with color and positioning of background overlay
- Add event propagation control to prevent interference with parent components
> fix automatic scroll on popover open

- packages/icons/package.json
> v2.2.1 for pcln-icons

- docs/package-lock.json
- re-generated package-lock.json to fix build
> Fix: Broken Docs Build

- package-lock.json
- packages/modal/test/__snapshots__/Headers.js.snap
Fix the current 🔴  CI in master to be 🍏 , due to an outdated merge of #585.
> Update snapshots for current master

- CONTRIBUTING.md
- README.md
- docs/README.md
- docs/next.config.js
- docs/pages/index.md
- docs/src/navigation.js
- packages/core/package.json
- packages/icons/README.md
To be done with: https://priceline.atlassian.net/wiki/spaces/Tech/pages/771424553/The+great+priceline+github+organization+rename+of+2019
> rename instances of priceline{labs,}

- CONTRIBUTING.md
- README.md
- docs/README.md
- docs/next.config.js
- docs/pages/index.md
- docs/src/navigation.js
- package-lock.json
- packages/autocomplete/package.json
- packages/core/package.json
- packages/icons/README.md
- Update references from `pricelinelabs` to `priceline`
- Clean up dependency mismatch with hoisted
> Post Organization Migration Housekeeping

- packages/core/src/Button.js
- packages/core/src/Step.js
- packages/core/storybook/Button.js
- packages/core/test/__snapshots__/Button.js.snap
- packages/core/test/__snapshots__/CloseButton.js.snap
- packages/core/test/__snapshots__/GreenButton.js.snap
- packages/core/test/__snapshots__/IconButton.js.snap
- packages/core/test/__snapshots__/IconField.js.snap
- packages/core/test/__snapshots__/OutlineButton.js.snap
- packages/core/test/__snapshots__/RedButton.js.snap
- packages/core/test/__snapshots__/Step.js.snap
- packages/core/test/__snapshots__/Stepper.js.snap
- packages/modal/test/__snapshots__/Headers.js.snap
- packages/popover/test/__snapshots__/Popover.js.snap
We want one consistent look and feel for the disabled button.
Before:
After:
> Standardize the disabled button

- COMPONENT_GUIDANCE.md
- CONTRIBUTING.md
- README.md
incorporated comments from the previous iteration
> Component guidance docs

- packages/core/src/Link.js
- packages/core/test/__snapshots__/BlockLink.js.snap
- packages/core/test/__snapshots__/Link.js.snap
- packages/modal/test/__snapshots__/Headers.js.snap
> Link uses dark shade one hover

- MIGRATING_to_v3.md
- package-lock.json
- package.json
- packages/popover/package.json
- packages/popover/src/Popover.js
- packages/popover/src/PopoverContent.js
- packages/popover/storybook/PopOver.js
- packages/popover/test/Popover.js
- packages/popover/test/__snapshots__/Popover.js.snap
- storybook/addons.js
> Add optional focus lock to Popover

- MIGRATING_to_v3.md
- package-lock.json
- package.json
- packages/core/src/Hug.js
- packages/core/src/Select.js
- packages/core/src/Step.js
- packages/core/storybook/Hug.js
- packages/core/test/Hug.js
- packages/core/test/__snapshots__/FormField.js.snap
- packages/core/test/__snapshots__/Select.js.snap
- packages/modal/test/__snapshots__/Headers.js.snap
- storybook/addons.js
Removed `<Icon>` from:
- Hug
- Step
- Select
> Remove Icon usage from Hug, Select, and Step

- MIGRATING_to_v3.md
- packages/core/src/Banner.js
- packages/core/storybook/Banner.js
- packages/core/test/Banner.js
- packages/core/test/__snapshots__/Banner.js.snap
- packages/modal/test/__snapshots__/Headers.js.snap
> Banner accepts node as header prop

- MIGRATING_to_v3.md
- packages/core/src/Avatar.js
- packages/core/src/index.js
- packages/core/storybook/Avatar.js
- packages/core/test/Avatar.js
- packages/core/test/__snapshots__/Avatar.js.snap
- packages/core/test/__snapshots__/Banner.js.snap
https://github.com/priceline/design-system/issues/645
Storybook example:
> Avatar component

- MIGRATING_to_v3.md
- packages/core/test/__snapshots__/Banner.js.snap
- packages/core/test/__snapshots__/FormField.js.snap
- packages/core/test/__snapshots__/IconField.js.snap
- packages/icons/src/Icon.js
- packages/icons/test/index.js
https://github.com/priceline/design-system/issues/654
> Default icon title is name

- packages/core/src/Tooltip.js
https://github.com/priceline/design-system/issues/270
> Remove align from tooltip

- packages/core/storybook/Icon.js
- packages/core/test/__snapshots__/Avatar.js.snap
- packages/core/test/__snapshots__/Banner.js.snap
- packages/core/test/__snapshots__/Breadcrumbs.js.snap
- packages/core/test/__snapshots__/Checkbox.js.snap
- packages/core/test/__snapshots__/CloseButton.js.snap
- packages/core/test/__snapshots__/FormField.js.snap
- packages/core/test/__snapshots__/IconField.js.snap
- packages/core/test/__snapshots__/Radio.js.snap
- packages/core/test/__snapshots__/Select.js.snap
- packages/core/test/__snapshots__/Step.js.snap
- packages/core/test/__snapshots__/Stepper.js.snap
- packages/icons/src/Svg.js
- packages/icons/test/__snapshots__/index.js.snap
- packages/modal/test/__snapshots__/Headers.js.snap
https://github.com/priceline/design-system/issues/441
> Responsive Icon Widths

- docs/pages/Theming.md
https://github.com/priceline/design-system/issues/593
> Add get palette color to docs

- MIGRATING_to_v3.md
- packages/core/package.json
- packages/core/src/Heading.js
- packages/core/src/Text.js
- packages/core/src/theme.js
- packages/core/storybook/Heading.js
- packages/core/test/Heading.js
- packages/core/test/__snapshots__/Avatar.js.snap
- packages/core/test/__snapshots__/Banner.js.snap
- packages/core/test/__snapshots__/Heading.js.snap
- packages/core/test/__snapshots__/IconField.js.snap
- packages/core/test/__snapshots__/theme.js.snap
https://github.com/priceline/design-system/issues/348
> Text shadows

- packages/autocomplete/src/index.js
- packages/autocomplete/test/__snapshots__/index.js.snap
- packages/core/src/index.js
- packages/modal/src/Modal.js
- packages/modal/src/ModalHeader.js
- packages/modal/src/SmallModalHeader.js
- packages/popover/src/Arrow.js
- packages/popover/src/Popover.js
- packages/popover/src/PopoverContent.js
Correcting the import for deprecatedPropType to come from pcln-design-system.
@sdalonzo
> Fix deprecatedPropType Import

- docs/pages/utilities/borders.md
- docs/pages/utilities/color.md
- docs/pages/utilities/getPaletteColor.md
- docs/pages/utilities/getTextColorOn.md
- docs/src/components.js
- docs/src/navigation.js
- packages/core/src/index.js
- packages/core/src/utils.js
- packages/core/test/utils.js
- adding documentation for utilities borders, color, getPaletteColor and getTextColorOn
- added unit tests for all utilities
> Utilities docs and unit tests

- packages/core/src/Banner.js
- packages/core/test/__snapshots__/Banner.js.snap
Addresses https://github.com/priceline/design-system/pull/644#discussion_r349816261
> Improve resiliency of Banner's header

- packages/core/src/Avatar.js
> fix(icon-import): use icon from core

- packages/core/package.json
Published v3.1.0, this is the version bump
> pcln-design-system v3.1.0

- CONTRIBUTING.md
explain --tag beta is CONTRIBUTING doc, and use 1.'s only for automatic numbering
> feat(tag-beta): explain --tag beta

- package-lock.json
- packages/slider/src/rc-slider/Range.js
- packages/slider/src/rc-slider/Slider.js
This pr attempts to mark the LifeCycleMethod `componentWillReceiveProps` as `UNFASE_componentWillReceiveProps`
> Update Lifecycle method in slider

- packages/core/src/BackgroundImage.js
- packages/core/src/utils.js
- packages/core/storybook/BackgroundImage.js
- packages/core/test/BackgroundImage.js
- packages/core/test/__snapshots__/BackgroundImage.js.snap
- Add variation for parallax to the component `BackgroundImage`
- Update util function `applyVariations` to allow for variations other than color
- Add a test and storybook example, update snapshot
> Add parallax variation to BackgroundImage

- packages/popover/package.json
Version bump for this PR https://github.com/priceline/design-system/pull/731
> Version bump for pcln-popover

- packages/modal/package.json
For https://github.com/priceline/design-system/pull/727
> Bump modal version

- packages/autocomplete/package.json
- packages/autocomplete/src/index.js
- packages/autocomplete/storybook/Autocomplete.js
> Themeable Autosuggest

- packages/slider/package.json
- packages/slider/src/RangeSlider.js
- packages/slider/src/Slider.js
- packages/slider/src/styleSlider.js
- packages/slider/storybook/Slider.js
- packages/slider/test/__snapshots__/index.js.snap
> Themeable Slider

- packages/core/src/Step.js
- packages/core/src/Stepper.js
> Step propagate props

- packages/popover/README.md
- packages/popover/package.json
- packages/popover/src/Popover.js
- packages/popover/storybook/PopOver.js
This is a duplicate of https://github.com/priceline/design-system/pull/745 because I messed up the commit history. Addresses #741.
> Add props to control popover display

- packages/popover/package.json
Version bump for https://github.com/priceline/design-system/pull/746
> Bump popover version

- packages/core/src/Stamp.js
- packages/core/src/createTextStyles.js
- packages/core/src/utils.js
- packages/core/storybook/Stamp.js
- packages/core/test/Stamp.js
- packages/core/test/__snapshots__/Stamp.js.snap
- packages/core/test/__snapshots__/theme.js.snap
Closes #739 
Closes #740 
Small
Regular
Small Solid
Regular Solid
> Stamp: Small Variation

- packages/core/package.json
New stamp variation (solid) and the introduce of sizes to the stamp component (small / regular) #748 
Step and Stepper propagate props #749
> Bump core version to 3.3.0

- packages/core/src/Button.js
- packages/core/src/Link.js
- packages/core/storybook/Link.js
> Add button variations to the link component

- packages/core/src/Badge.js
- packages/core/src/Stamp.js
- packages/core/src/utils.js
- packages/core/storybook/Badge.js
- packages/core/storybook/Stamp.js
- packages/core/test/Badge.js
- packages/core/test/Stamp.js
- packages/core/test/__snapshots__/Badge.js.snap
- packages/core/test/__snapshots__/Stamp.js.snap
Closes #738 
- Added Badge small size
- Renamed Stamp regular size to medium
- Renamed Stamp regular variation to outline to be consistent with Button
- Renamed Stamp solid variation to fill to be consistent with Button
- Fixed border-color issue with fill variation of the Stamp
- Added Cartesian Storybook for Badge
- Added Cartesian Storybook for Stamp
> Small Badge and Rename Stamp Variations and Size

- docs/pages/Modal.md
- packages/modal/src/Modal.js
- packages/modal/storybook/Modal.js
- packages/modal/test/Modal.js
> Fullscreen modal

- packages/modal/package.json
This is for @James300's timeout changes and my fullScreen prop
> Bump modal version to 3.3.0

- packages/core/src/Link.js
- packages/core/test/__snapshots__/BlockLink.js.snap
> Fix Link Button Styles

- packages/core/package.json
- packages/popover/package.json
Draft release https://github.com/priceline/design-system/releases/edit/untagged-4e0648ea9c7af9dd5b13
> Bump popover to 3.3.1

- .github./PULL_REQUEST_TEMPLATE.md
- .github/ISSUE_TEMPLATE.md
- Added templates for Issue and Pull requests
Fixes: #776
> Added .github folder

- .github./PULL_REQUEST_TEMPLATE.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
There was an additional folder created in the Last PR. It fixes that.
> Delete .github. folder

- .github./PULL_REQUEST_TEMPLATE.md
- package-lock.json
- **What does this PR do?**
- **Any background context you want to provide?**
- **Screenshot(s)**
> npm audit fix, delete .github. directory

- plop-templates/core/index.js.hbs
- plop-templates/core/{{componentName}}.js.hbs
- plop-templates/core/{{componentName}}.spec.js.hbs
- plop-templates/core/{{componentName}}.stories.js.hbs
- plopfile.js
> Update plop template to use new folder structure

- .storybook/addons.js
- .storybook/main.js
- .storybook/presets.js
- .storybook/preview.js
- packages/autocomplete/storybook/Autocomplete.stories.js
- packages/modal/storybook/Modal.stories.js
- packages/popover/storybook/Popover.stories.js
- packages/slider/src/rc-slider/Range.js
- packages/slider/src/rc-slider/Slider.js
- packages/slider/storybook/Slider.stories.js
> Fix Storybook configuration and sub-package stories

- packages/modal/src/SmallModalHeader.js
- packages/slider/src/RangeSlider.js
- packages/slider/src/Slider.js
Resolves the 3 issues logged by LGTM against DS: https://lgtm.com/projects/g/priceline/design-system/alerts/?mode=list
> Fix a few LGTM alerts (unused imports)

- packages/types/types/index.d.ts
- packages/types/types/test.tsx
> Add prop types for link, typography, and a11y components

- docs/pages/Modal.md
- packages/modal/README.md
- packages/modal/package.json
- packages/modal/src/Modal.js
- packages/modal/storybook/Modal.stories.js
- packages/modal/test/Modal.js
Resolves https://github.com/priceline/design-system/issues/768
Looks like the pre-commit hook linted a few things, I can revert that if it was incorrect.
> Add aria-label / aria-lablledby props to Modal

- packages/types/types/index.d.ts
- packages/types/types/test.tsx
> Add prop types for image components

- package-lock.json
- packages/types/package.json
- packages/types/types/index.d.ts
- packages/types/types/test.tsx
Also adds a script to format the `types` folder.
Resolves #795
> Add types to exported utility functions

- packages/types/types/index.d.ts
- packages/types/types/test.tsx
> Add types for Breadcrumbs and Stepper

- README.md
- docs/package-lock.json
- docs/package.json
- docs/src/NavLink.js
- docs/src/SideNav.js
- docs/src/components.js
- docs/src/navigation.js
> Fix package vulnerabilities in the next.js docsite

- packages/popover/storybook/Popover.stories.js
> Fix style bug on popover docs page by disabling stories slot

- packages/types/types/index.d.ts
- packages/types/types/test.tsx
- Types for Badge, ToggleBadge, and RatingBadge
> Add prop types for badge components

- packages/types/types/index.d.ts
- packages/types/types/test.tsx
> Add deprecated props to components that already have declarations

- packages/core/src/Banner/Banner.js
- packages/types/types/index.d.ts
- packages/types/types/test.tsx
Resolves https://github.com/priceline/design-system/issues/787
> Add prop types for static display components

- packages/types/types/index.d.ts
- packages/types/types/test.tsx
- packages/types/types/tsconfig.json
- Resolves #835 
- Resolves #836 (same fix for #835)
- Resolves #837
> Typescript bugfixes

- packages/core/src/Card/Card.js
- packages/core/src/Card/__snapshots__/Card.spec.js.snap
> Fix duplicate box-shadow in Card

- package-lock.json
- packages/core/package.json
I also included the updated lockfile after running `npm run prepare` with my public npmrc profile
> Version bump for 3.5 and updating lockfile

- packages/core/package.json
- packages/types/types/index.d.ts
- packages/types/types/test.tsx
> Add HTML prop types to some components' declarations

- packages/core/README.md
> Add README to core project

- packages/popover/package.json
adding styled-system dependency
> Bugfix - 'themeGet' not found in 'styled-system'

- codemods/icons-v2-to-v3/iconsV2toV3.js
> Remove unused variables

- packages/slider/storybook/Slider.stories.js
Updating the stories for the slider package as one was not working and others were missing aria props.
> Update Slider.stories.js for a11y violations

- packages/autocomplete/README.md
- packages/icons/README.md
- packages/modal/README.md
- packages/popover/README.md
- packages/slider/README.md
> Add note about ThemeProvider to subpackage readmes

- docs/pages/iconography.js
- docs/src/ColorCard.js
- docs/src/SideNav.js
- docs/src/components.js
- Remove usage of `Icon` component, replace with `pcln-icons`
- Remove SVG download link
- Update deprecated properties and colours to be palette colours
> Update iconography docs

- packages/core/src/Hug/Hug.js
- packages/core/src/Hug/Hug.stories.js
Yuriy noticed that the hug icon was not aligned properly, this was caused by the styled-system props (and size) being nested within a style object causing these props to have zero effect.
> Fixed Hug Props

- packages/core/package.json
For this release: https://github.com/priceline/design-system/releases/tag/v3.6.0
> Release - Core 3.6.0

- packages/core/package.json
https://github.com/priceline/design-system/releases/tag/v3.6.1
> Release 3.6.1

- packages/popover/package.json
> Popover v3.4.0

- packages/icons/src/Icon.js
https://github.com/priceline/design-system/issues/913
> issue(913): Add runtime deprecation for unnamed Icon

- common/changes/pcln-design-system/buttom-stamp-font-weight_2020-10-14-22-00.json
- packages/core/src/Button/Button.js
- packages/core/src/Button/Button.spec.js
- packages/core/src/CloseButton/__snapshots__/CloseButton.spec.js.snap
- packages/core/src/IconButton/__snapshots__/IconButton.spec.js.snap
- packages/core/src/IconField/__snapshots__/IconField.spec.js.snap
- packages/core/src/Stamp/Stamp.js
- packages/core/src/Stamp/__snapshots__/Stamp.spec.js.snap
- packages/core/src/Step/__snapshots__/Step.spec.js.snap
- packages/core/src/Stepper/__snapshots__/Stepper.spec.js.snap
- packages/modal/src/__snapshots__/Headers.spec.js.snap
- packages/popover/src/Popover/__snapshots__/Popover.spec.js.snap
https://github.com/priceline/design-system/issues/476 - Removing hard coded font-weights from button / stamp.
> Remove hard coded font-weight from button / stamp

- common/changes/pcln-design-system/checkout-noChange-not-required_2020-10-26-13-20.json
- packages/core/src/Checkbox/Checkbox.js
> Update onChange of Checkbox to remove isRequired

- common/changes/pcln-design-system/update-stamp-size-prop_2020-11-04-16-03.json
- packages/core/src/Stamp/Stamp.js
- packages/core/src/Stamp/Stamp.stories.js
- packages/core/src/theme/theme.js
- packages/core/src/utils/utils.js
- packages/core/src/utils/utils.spec.js
https://5a85e56213417800200978ab-zetreramsm.chromatic.com/?path=/story/stamp--pass-an-array-of-sizes
Update `Stamp` so its size property can also accept an array 
_(Shoutout: @pcln-james helped out immensely with this)_
> allow sizes prop to accept an array

- common/changes/pcln-design-system/fix-font-weight-regression_2020-11-13-18-04.json
- packages/core/src/Button/Button.js
- packages/core/src/Button/Button.spec.js
- packages/core/src/CloseButton/__snapshots__/CloseButton.spec.js.snap
- packages/core/src/IconButton/__snapshots__/IconButton.spec.js.snap
- packages/core/src/IconField/__snapshots__/IconField.spec.js.snap
- packages/core/src/Step/__snapshots__/Step.spec.js.snap
- packages/core/src/Stepper/__snapshots__/Stepper.spec.js.snap
- packages/modal/src/__snapshots__/Headers.spec.js.snap
- packages/popover/src/Popover/__snapshots__/Popover.spec.js.snap
> Fix font-weight regression

- CONTRIBUTING.md
- common/changes/pcln-design-system/new-menu-package_2020-11-16-19-52.json
- common/changes/pcln-design-system/new-menu-package_2020-12-01-17-51.json
- common/changes/pcln-menu/new-menu-package_2020-11-16-19-52.json
- common/config/rush/pnpm-lock.yaml
- packages/core/src/Stamp/Stamp.js
- packages/core/src/index.js
- packages/menu/.eslintignore
- packages/menu/.eslintrc.js
- packages/menu/README.md
- packages/menu/babel.config.js
- packages/menu/jest.config.js
- packages/menu/package.json
- packages/menu/src/Menu/Menu.js
- packages/menu/src/Menu/Menu.spec.js
- packages/menu/src/Menu/Menu.stories.js
- packages/menu/src/Menu/index.js
- packages/menu/src/MenuItem/MenuItem.js
- packages/menu/src/MenuItem/MenuItem.spec.js
- packages/menu/src/MenuItem/MenuItem.stories.js
- packages/menu/src/MenuItem/index.js
- packages/menu/src/MenuList/MenuList.js
- packages/menu/src/MenuList/MenuList.spec.js
- packages/menu/src/MenuList/MenuList.stories.js
- packages/menu/src/MenuList/index.js
- packages/menu/src/index.js
- packages/menu/test/jest.setup.js
- packages/menu/test/mocks/Menu.js
- packages/menu/test/testing-library.js
- rush.json
Closes #704 
Took some inspiration from the material-ui Menu component https://material-ui.com/components/menus/
> New pcln-menu package

- common/changes/pcln-design-system/fix-iconfield-error_2020-12-06-01-57.json
- packages/core/src/IconField/IconField.js
> Fix error when using Icon in pcln-icons with IconField

- common/changes/pcln-popover/popover-pass-theme_2020-12-05-00-29.json
- packages/popover/src/Popover/Popover.spec.js
- packages/popover/src/Popover/Popover.stories.js
- packages/popover/src/Popover/__snapshots__/Popover.spec.js.snap
- packages/popover/src/PopoverContent/PopoverContent.js
> Pass parent theme to popover content

- apps/docs/pages/Breakpoints.md
- apps/docs/src/navigation.js
I'm tired of having to find and convert these values each time I need to reference them.
> Create docsite page for breakpoints

- apps/docs/src/components.js
- common/changes/pcln-design-system/withComponent-to-as-prop_2020-12-21-17-52.json
- packages/core/src/Banner/__snapshots__/Banner.spec.js.snap
- packages/core/src/Hug/Hug.stories.js
- packages/core/src/ShadowEffect/ShadowEffect.spec.js
- packages/core/src/Text/Text.js
- packages/core/src/Text/Text.stories.js
- packages/core/src/stories/Colors.stories.js
> Change withComponent to as prop

- common/changes/pcln-icons/985-icon-line-height_2020-12-28-20-47.json
- packages/core/src/Avatar/__snapshots__/Avatar.spec.js.snap
- packages/core/src/Banner/__snapshots__/Banner.spec.js.snap
- packages/core/src/Breadcrumbs/__snapshots__/Breadcrumbs.spec.js.snap
- packages/core/src/Checkbox/__snapshots__/Checkbox.spec.js.snap
- packages/core/src/CloseButton/__snapshots__/CloseButton.spec.js.snap
- packages/core/src/FormField/__snapshots__/FormField.spec.js.snap
- packages/core/src/IconButton/__snapshots__/IconButton.spec.js.snap
- packages/core/src/IconField/__snapshots__/IconField.spec.js.snap
- packages/core/src/Radio/__snapshots__/Radio.spec.js.snap
- packages/core/src/Select/__snapshots__/Select.spec.js.snap
- packages/core/src/Step/__snapshots__/Step.spec.js.snap
- packages/core/src/Stepper/__snapshots__/Stepper.spec.js.snap
- packages/icons/src/Icon.stories.js
- packages/icons/src/Svg.js
- packages/modal/src/__snapshots__/Headers.spec.js.snap
> Set line-height on Icon

- .github/workflows/continuous-integration.yml
- apps/docs/package.json
- apps/storybook/package.json
- common/changes/pcln-autocomplete/pnpm-workspaces_2020-12-02-22-59.json
- common/changes/pcln-design-system/pnpm-workspaces_2020-12-02-22-59.json
- common/changes/pcln-icons/pnpm-workspaces_2020-12-02-22-59.json
- common/changes/pcln-menu/pnpm-workspaces_2020-12-02-22-59.json
- common/changes/pcln-modal/pnpm-workspaces_2020-12-02-22-59.json
- common/changes/pcln-popover/pnpm-workspaces_2020-12-02-22-59.json
- common/changes/pcln-slider/pnpm-workspaces_2020-12-02-22-59.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- packages/autocomplete/package.json
- packages/core/package.json
- packages/icons/package.json
- packages/icons/src/__snapshots__/index.spec.js.snap
- packages/menu/package.json
- packages/modal/package.json
- packages/popover/package.json
- packages/slider/package.json
- rush.json
- tools/babel-preset/package.json
- tools/create-release-notes/package.json
- tools/types/.eslintrc.js
- tools/types/package.json
> Use PNPM workspaces

- apps/docs/pages/Button.md
- common/changes/pcln-design-system/button-variations_2021-02-05-13-57.json
- packages/core/src/Button/Button.js
- packages/core/src/Button/Button.spec.js
- packages/core/src/Button/Button.stories.js
- packages/core/src/CloseButton/__snapshots__/CloseButton.spec.js.snap
- packages/core/src/IconButton/__snapshots__/IconButton.spec.js.snap
- packages/core/src/IconField/__snapshots__/IconField.spec.js.snap
- packages/core/src/Step/__snapshots__/Step.spec.js.snap
- packages/core/src/Stepper/__snapshots__/Stepper.spec.js.snap
- packages/icons/src/__snapshots__/index.spec.js.snap
- packages/modal/src/__snapshots__/Headers.spec.js.snap
- packages/popover/src/Popover/__snapshots__/Popover.spec.js.snap
[Invision](https://priceline.invisionapp.com/d/main/#/console/17267042/444026802/preview) for different button variations
Added new variations: plain, lightFill and subtle to Button
Added css styling for focus state in Fill variation
(Will likely be renaming the lightFill variation after discussing with Wes)
> add new button variations

- common/changes/pcln-menu/popover-button-props-and-full-width_2021-02-22-19-26.json
- common/changes/pcln-popover/popover-button-props-and-full-width_2021-02-22-19-26.json
- packages/menu/src/Menu/Menu.js
- packages/menu/src/Menu/Menu.stories.js
- packages/menu/src/MenuItem/MenuItem.js
- packages/popover/src/PopoverContent/PopoverContent.js
* Popover prop `buttonProps` for controlling the main buttons props
* Menu prop `buttonProps` for controlling the main buttons props
* Popover accepts a string width now too
> Menu and Popover buttonProps

- apps/docs/pages/Popover.md
> Add prop to overlay docs

- common/changes/pcln-design-system/responsive-sizes-for-avatar_2021-03-12-21-14.json
- packages/core/src/Avatar/Avatar.js
- packages/core/src/Avatar/Avatar.spec.js
- packages/core/src/Avatar/Avatar.stories.js
- packages/core/src/Avatar/__snapshots__/Avatar.spec.js.snap
Supporting an array of sizes for responsiveness.
AltText prop for controlling the avatar alt
> Responsive sizes for avatar

- common/changes/pcln-menu/menu-clickable-component_2021-03-22-20-32.json
- packages/menu/src/Menu/Menu.js
- packages/menu/src/Menu/Menu.spec.js
- packages/menu/src/Menu/Menu.stories.js
* Changed `onChange` to `onClick` being used for the click event for chips to fix a bug
* Added `clickableNode` prop to Menu to support an clickable component being used as the base component to open a menu
> Menu clickable component

- common/changes/pcln-autocomplete/spinner-component_2021-04-21-19-02.json
- common/changes/pcln-design-system/spinner-component_2021-04-21-19-02.json
- common/changes/pcln-icons/spinner-component_2021-04-21-19-02.json
- common/changes/pcln-menu/spinner-component_2021-04-21-19-02.json
- common/changes/pcln-modal/spinner-component_2021-04-21-19-02.json
- common/changes/pcln-popover/spinner-component_2021-04-21-19-02.json
- common/changes/pcln-slider/spinner-component_2021-04-21-19-02.json
- packages/core/jest.config.js
- packages/core/src/Spinner/Spinner.js
- packages/core/src/Spinner/Spinner.spec.js
- packages/core/src/Spinner/Spinner.stories.args.js
- packages/core/src/Spinner/Spinner.stories.js
- packages/core/src/Spinner/index.js
A simple Spinner to indicate loading or saving.
* full color support
* small / medium / large sizes for consistent design
* supports overriding colors and width/height
> Create new spinner component

- common/changes/pcln-autocomplete/font-style-and-text-decoration_2021-05-13-21-55.json
- common/changes/pcln-design-system/font-style-and-text-decoration_2021-05-13-21-55.json
- common/changes/pcln-menu/font-style-and-text-decoration_2021-05-13-21-55.json
- common/changes/pcln-modal/font-style-and-text-decoration_2021-05-13-21-55.json
- common/changes/pcln-popover/font-style-and-text-decoration_2021-05-13-21-55.json
- common/changes/pcln-slider/font-style-and-text-decoration_2021-05-13-21-55.json
- packages/core/src/Text/Text.js
- packages/core/src/Text/Text.spec.js
- packages/core/src/Text/Text.stories.js
@michael-alterio asked for this feature and here it is, sorry it took a few days.
> Font style and text decoration

- packages/menu/CHANGELOG.json
- packages/menu/CHANGELOG.md
- packages/menu/package.json
I didn't build the version when publish, also used the wrong publish command.
> patch pcln-menu for another release

- common/changes/pcln-design-system/image-crop-support-2_2022-01-13-20-06.json
- packages/core/src/BackgroundImage/BackgroundImage.js
- packages/core/src/BackgroundImage/BackgroundImage.spec.js
- packages/core/src/BackgroundImage/BackgroundImage.stories.args.js
- packages/core/src/BackgroundImage/BackgroundImage.stories.js
- packages/core/src/BackgroundImage/__snapshots__/BackgroundImage.spec.js.snap
- packages/core/src/Image/Image.js
- packages/core/src/Image/Image.spec.js
- packages/core/src/Image/Image.stories.args.js
- packages/core/src/Image/Image.stories.js
- packages/core/src/theme/theme.js
- packages/core/src/utils/attrs/boxShadowAttrs.js
> Add support for borderRadius and boxShadow to Image

- common/changes/pcln-icons/fix-logout-icon_2022-01-18-21-18.json
- common/config/rush/pnpm-lock.yaml
- packages/icons/svg/logout.svg
> Remove extra polgyon from logout icon

- common/changes/pcln-design-system/layout-variation-prop_2022-02-10-13-51.json
- packages/core/src/Layout/Layout.stories.tsx
- packages/core/src/Layout/Layout.tsx
- Add prop type descriptions
- Support null children
- Add new story
> Improve Layout stories, make variation required

- common/changes/pcln-slider/update-rc-slider_2022-03-07-13-35.json
- packages/slider/README.md
Forgot to add a changefile in https://github.com/priceline/design-system/pull/1131
> Changefile for pcln-slider

- common/changes/pcln-carousel/feature-carousel-variant_2022-03-09-18-43.json
- packages/carousel/src/ArrowButton/ArrowButton.js
- packages/carousel/src/ArrowButton/ArrowButton.styles.js
- packages/carousel/src/Carousel.js
- packages/carousel/src/Carousel.stories.js
* backwards compatible/default colors still in place
> feat(cv): allow alternate arrow button colors

- common/changes/pcln-modal/feature-title-font-size-modal_2022-03-16-20-33.json
- packages/modal/src/Modal.spec.js
- packages/modal/src/Modal.stories.js
- packages/modal/src/ModalHeader.js
- packages/modal/src/SmallModalHeader.js
- packages/modal/src/__snapshots__/Headers.spec.js.snap
adds new "textStyle" and space props to ModalHeader to support following design
> adds textStyle prop to ModalHeader

- common/changes/pcln-carousel/chore-button-padding_2022-03-31-16-06.json
- packages/carousel/src/Carousel.js
* fixes small bug from previous merge
> chore(bp): replace pr with pl for prev arrow button

- common/changes/pcln-design-system/UXPT-2924-filter-chip-value-prop_2022-04-22-16-39.json
- packages/core/src/Chip/FilterChip/FilterChip.stories.tsx
- packages/core/src/Chip/FilterChip/FilterChip.tsx
Adds `value` prop to FilterChip
> feat(UXPT-2924): add value prop to FilterChip

- common/changes/pcln-design-system/add-toggle-name_2022-05-12-16-51.json
- common/config/rush/pnpm-lock.yaml
- packages/core/package.json
- packages/core/src/Toggle/Toggle.tsx
This is needed for Toggle to work with `<form>` elements
> Add name prop to Toggle

- packages/core/src/Button/Button.stories.mdx
Also removes an errant comment
> Add args table to Button docs page

- common/changes/pcln-design-system/button-white-variation_2022-05-31-14-53.json
- packages/core/src/Button/Button.spec.tsx
- packages/core/src/Button/Button.stories.args.ts
- packages/core/src/Button/Button.tsx
This adds variation `white` to Button.
> Add white variation to Button

- common/changes/pcln-carousel/feat-PKG-14737-Add-currentSlide-prop-v2_2022-07-08-14-05.json
- packages/carousel/src/Carousel.js
- packages/carousel/src/Carousel.spec.js
Add a property to allow the Carousel to start from a specific slide.
> feat(PKG-14737): Add currentSlide prop to Carousel

- common/changes/pcln-design-system/feat-unselected-checkbox-color_2022-07-18-19-22.json
- packages/core/src/Checkbox/Checkbox.stories.tsx
- packages/core/src/Checkbox/Checkbox.tsx
- packages/core/src/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
Add a property to allow for color change for unselected checkboxes.
> feat(unselected-checkbox-color): add prop to select checkbox color

- packages/core/src/Link/Link.stories.tsx
* Added a storybook example of how to use a Link with text styles
* No change log required as this does not need to be published.
> Added an example of a Link with text styles

- .github/workflows/on-main.yml
Fixes this Actions failure: https://github.com/priceline/design-system/runs/7728419042?check_suite_focus=true#step:5:79
> Use Node 14 in on-main workflow

- packages/core/src/stories/Colors.stories.tsx
Support swapping the theme using a storybook addon
> Support theme swapping in palette story

- .github/workflows/npm-publish.yaml
Adds comments and fixes the ref used when creating GH releases
> Fix NPM publish changes not being merged back to main

- common/changes/pcln-menu/feature-RC-21569-sort-icon-menu-styles_2022-09-21-03-43.json
- packages/core/src/Banner/Banner.tsx
- packages/core/src/CloseButton/CloseButton.tsx
- packages/core/src/Select/Select.tsx
- packages/menu/src/Menu/Menu.stories.js
- packages/menu/src/MenuItem/MenuItem.js
- packages/menu/src/MenuItem/MenuItem.spec.js
- packages/menu/src/MenuItem/MenuItem.stories.js
- packages/menu/src/MenuList/MenuList.stories.js
- Updated background-color and color for MenuItem default, selected and hover states
**MenuItem**
**Default Color**
**Custom Color**
**With Icon**
> feature(RC-21569): adds new sort icon and updated MenuItem styles

- common/changes/pcln-design-system/update-button-valid-border-radii_2022-10-18-15-37.json
- packages/core/src/Button/Button.tsx
I noticed that several of our border radii values do nothing for the Button component. I fixed this by fetching from the sources and mapping the keys to an array.
> Update button valid border radii

- common/changes/pcln-design-system/PPN-59016-v4-update-link-and-textColorOn_2022-11-08-21-32.json
- packages/core/src/Link/Link.spec.tsx
- packages/core/src/Link/Link.stories.args.ts
- packages/core/src/Link/Link.stories.tsx
- packages/core/src/Link/Link.tsx
- packages/core/src/__test__/mocks/colors.ts
- packages/core/src/utils/utils.spec.ts
- packages/core/src/utils/utils.ts
Backporting https://github.com/priceline/design-system/pull/1216 to DSv4
> Update link and textColorOn disabled states for v4

- common/changes/pcln-design-system/checkbox-indeterminate-story_2023-01-23-15-27.json
- packages/core/src/Checkbox/Checkbox.spec.tsx
- packages/core/src/Checkbox/Checkbox.tsx
- packages/core/src/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
This is the v4 implementation of https://github.com/priceline/design-system/pull/1248
> Fix bug with indeterminate Checkbox

- common/changes/pcln-design-system/add-buttonChip-state_2023-02-17-19-38.json
- packages/core/src/Chip/ButtonChip/ButtonChip.stories.tsx
- packages/core/src/Chip/ChipContent/ChipContent.spec.tsx
- packages/core/src/Chip/ChipContentWrapper.tsx
- packages/core/src/Chip/ChoiceChip/ChoiceChip.stories.tsx
- packages/core/src/Chip/FilterChip/FilterChip.stories.tsx
Adding a new state for the buttonChip (disabled + selected) and updating its color to match button.
Before:
After:
> add buttonChip state

- common/changes/pcln-design-system/v4-fix-two-prop-type-warnings_2023-02-28-21-26.json
- common/changes/pcln-menu/v4-fix-two-prop-type-warnings_2023-02-28-21-26.json
- packages/core/src/FormField/FormField.spec.tsx
- packages/core/src/FormField/FormField.tsx
- packages/core/src/Tooltip/Tooltip.stories.tsx
- packages/menu/src/Menu/Menu.js
v4 update for https://github.com/priceline/design-system/pull/1266
> fix(v4): two prop type warnings

- common/changes/pcln-design-system/create-toast-component_2023-04-03-19-52.json
- packages/core/src/Animate/Animate.tsx
- packages/core/src/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
- packages/core/src/Flex/index.ts
- packages/core/src/Toast/Toast.spec.tsx
- packages/core/src/Toast/Toast.stories.args.ts
- packages/core/src/Toast/Toast.stories.tsx
- packages/core/src/Toast/Toast.tsx
- packages/core/src/Toast/index.ts
- packages/core/src/ToastProvider/ToastProvider.spec.tsx
- packages/core/src/ToastProvider/ToastProvider.stories.tsx
- packages/core/src/ToastProvider/ToastProvider.tsx
- packages/core/src/ToastProvider/index.ts
- packages/core/src/__test__/mocks/toasts.tsx
- packages/core/src/index.ts
* Create Toast component
* Create ToastProvider
* Create useToast hook
Storybook: https://5a85e56213417800200978ab-ipmautczgf.chromatic.com/?path=/story/core-toastprovider--toast-provider
https://user-images.githubusercontent.com/62619213/225826472-8baffaf0-cd85-43f3-9fbd-e8372817467f.mov
> Create core Toast component

- common/changes/pcln-carousel/replace-use-of-usetheme_2023-04-11-17-19.json
- common/changes/pcln-design-system/replace-use-of-usetheme_2023-04-11-17-19.json
- common/changes/pcln-docs-utils/replace-use-of-usetheme_2023-04-11-17-19.json
- common/changes/pcln-menu/replace-use-of-usetheme_2023-04-11-17-19.json
- common/changes/pcln-modal/replace-use-of-usetheme_2023-04-11-17-19.json
- common/changes/pcln-popover/replace-use-of-usetheme_2023-04-11-17-19.json
Forgot to include in https://github.com/priceline/design-system/pull/1294
> Use withTheme instead of useTheme in ToastProvider

- common/changes/pcln-design-system/feat-SITE-20797-add-width-prop_2023-05-19-20-49.json
- packages/core/src/Chip/ButtonChip/ButtonChip.stories.tsx
- packages/core/src/Chip/ButtonChip/ButtonChip.tsx
- packages/core/src/Chip/ChipContentWrapper.tsx
- [SITE-20797](https://priceline.atlassian.net/browse/SITE-20797)
Add optional width prop to Button Chip Component
> feat(SITE-20797): Add width Prop

- common/changes/pcln-design-system/UXPT-4804-add-disabled-state-to-input-and-select_2023-07-10-20-23.json
- packages/core/src/Box/Box.tsx
- packages/core/src/FormField/FormField.spec.tsx
- packages/core/src/FormField/FormField.stories.tsx
- packages/core/src/FormField/FormField.tsx
- packages/core/src/FormField/__snapshots__/FormField.spec.tsx.snap
- packages/core/src/Input/Input.spec.tsx
- packages/core/src/Input/Input.stories.args.ts
- packages/core/src/Input/Input.stories.tsx
- packages/core/src/Input/Input.tsx
- packages/core/src/Input/__snapshots__/Input.spec.tsx.snap
- packages/core/src/Select/Select.spec.tsx
- packages/core/src/Select/Select.stories.args.ts
- packages/core/src/Select/Select.stories.tsx
- packages/core/src/Select/Select.tsx
- packages/core/src/Select/__snapshots__/Select.spec.tsx.snap
Closes:
* https://priceline.atlassian.net/browse/UXPT-4804
* https://priceline.atlassian.net/browse/UXPT-4822
This will make it easier for us to build forms that require disabled states.
> feat(UXPT-4804): Add disabled state for Input and Select

- apps/storybook/.storybook/main.ts
- apps/storybook/package.json
- common/changes/pcln-design-system/UXPT-4962-create-chat-header-component_2023-07-11-18-37.json
- common/config/rush/pnpm-lock.yaml
- packages/core/src/ChatHeader/ChatHeader.stories.tsx
- packages/core/src/ChatHeader/ChatHeader.tsx
- packages/core/src/ChatHeader/index.ts
https://priceline.atlassian.net/browse/UXPT-4962
* Add `@storybook/addon-interactions` to the storybook addons - this enables interaction tests in storybook
* Create `ChatHeader` components
* Use storybook interaction tests to cover `ChatHeader`
> Create ChatHeader component

- common/changes/pcln-design-system/more-color-scheme-support_2023-07-11-17-25.json
- packages/core/config/jest.config.json
- packages/core/src/Badge/Badge.stories.tsx
- packages/core/src/Badge/Badge.tsx
- packages/core/src/Box/Box.tsx
- packages/core/src/Card/Card.spec.tsx
- packages/core/src/Card/Card.tsx
- packages/core/src/Card/__snapshots__/Card.spec.tsx.snap
- packages/core/src/Hug/Hug.stories.tsx
- packages/core/src/Hug/Hug.styled.ts
- packages/core/src/Hug/Hug.tsx
- packages/core/src/Hug/__snapshots__/Hug.spec.tsx.snap
- packages/core/src/Stamp/Stamp.stories.tsx
- packages/core/src/Stamp/Stamp.tsx
- packages/core/src/storybook/args/index.ts
- packages/core/src/theme/theme.ts
- packages/core/src/utils/createColorScheme.ts
- rigs/component/profiles/react/config/jest.config.json
> Add colorScheme prop to Hug

- common/changes/pcln-design-system/UXPT-4964-create-chat-message-component_2023-07-11-23-00.json
- packages/core/src/ChatMessage/ChatMessage.stories.tsx
- packages/core/src/ChatMessage/ChatMessage.tsx
- packages/core/src/ChatMessage/index.ts
https://priceline.atlassian.net/browse/UXPT-4964
Create `ChatMessage` component
> feat(UXPT-4964): Create ChatMessage component

- common/changes/pcln-design-system/feat-UXPT-4881-accordion_2023-07-17-15-35.json
- common/config/rush/pnpm-lock.yaml
- packages/core/package.json
- packages/core/src/Accordion/Accordion.stories.tsx
- packages/core/src/Accordion/Accordion.styled.tsx
- packages/core/src/Accordion/Accordion.tsx
- packages/core/src/Accordion/index.tsx
Created Accordion package component using Radix library
> feat(UXPT-4881): accordion

- common/changes/pcln-design-system/fix-Image-unable-to-be-loaded_2023-07-25-20-49.json
- packages/core/src/RadioCheckToggleCard/RadioCheckToggleCard.stories.tsx
**Component**
Core / RadioCheckToggleCard
**Before**
**After**
> Fix image unable to be loaded

- common/changes/pcln-design-system/UXPT-4967-chat-message-separator_2023-07-25-22-26.json
- packages/core/src/ChatMessageSeparator/ChatMessageSeparator.stories.tsx
- packages/core/src/ChatMessageSeparator/ChatMessageSeparator.tsx
- packages/core/src/ChatMessageSeparator/index.ts
- packages/core/src/RadioCheckToggleCard/__snapshots__/RadioCheckToggleCard.spec.tsx.snap
- packages/core/src/Text/Text.tsx
- packages/core/src/utils/attrs/typographyAttrs.ts
- packages/core/src/utils/utils.ts
* Add textWrap prop support to Text component
* Create `ChatMessageSeparator` component
> feat(UXPT-4967): Create ChatMessageSeparator component

- common/changes/pcln-design-system/UXPT-4958-create-chat-trigger_2023-07-21-16-13.json
- common/changes/pcln-icons/UXPT-4958-create-chat-trigger_2023-07-21-16-13.json
- packages/core/src/Absolute/Absolute.tsx
- packages/core/src/Absolute/index.ts
- packages/core/src/Animate/Animate.tsx
- packages/core/src/Button/Button.tsx
- packages/core/src/ChatTrigger/ChatTrigger.stories.tsx
- packages/core/src/ChatTrigger/ChatTrigger.tsx
- packages/core/src/ChatTrigger/index.ts
- packages/core/src/FloatingActionButton/FloatingActionButton.stories.tsx
- packages/core/src/FloatingActionButton/FloatingActionButton.styled.tsx
- packages/core/src/FloatingActionButton/FloatingActionButton.tsx
- packages/core/src/FloatingActionButton/index.ts
- packages/core/src/RadioCheckToggleCard/__snapshots__/RadioCheckToggleCard.spec.tsx.snap
- packages/icons/src/__snapshots__/index.spec.js.snap
https://priceline.atlassian.net/browse/UXPT-4958
Created Floating Action Button.
Created ChatTrigger that wraps the FAB component but sets it to the bottom right corner of the screen. I did it this way because the Figma designs make it seem like we might add alternative variations for the ChatTrigger component with FAB being just one of them.
> feat(UXPT-4958): Create ChatTrigger component

- common/changes/pcln-design-system/AIR-56045-darkshimmer_2023-07-27-17-36.json
- common/changes/pcln-design-system/AIR-56045-darkshimmer_2023-07-27-19-53.json
- common/changes/pcln-design-system/AIR-56045-darkshimmer_2023-07-28-15-01.json
- packages/core/src/Shimmer/Shimmer.spec.tsx
- packages/core/src/Shimmer/Shimmer.stories.tsx
- packages/core/src/Shimmer/Shimmer.tsx
- packages/core/src/Shimmer/constants.ts
Figma:  [url](https://www.figma.com/file/1lLCo0ZnO1RyMDEbnnS0by/Web-Design-System?type=design&node-id=3988-38808&mode=design&t=HQLbdj5HoEHLWIEw-0)
Jira: [AIR-56045](https://priceline.atlassian.net/browse/AIR-56045)
> feat(AIR-56045): add light and dark props to shimmer

- common/changes/pcln-design-system/feat-HTL-91943-collapsible-filters_2023-09-21-14-48.json
- packages/core/src/Accordion/Accordion.stories.tsx
- packages/core/src/Accordion/Accordion.styled.tsx
- packages/core/src/Accordion/Accordion.tsx
using space prop to add configurable padding
storybook: https://5a85e56213417800200978ab-tbjmfkmxiz.chromatic.com/?path=/docs/accordion--docs
> feat(HTL-91943): adjust accordion padding

- common/changes/pcln-carousel/add-hover-on-side-arrow_2023-10-21-00-49.json
- common/config/rush/pnpm-lock.yaml
- packages/carousel/package.json
- packages/carousel/src/ArrowButton/ArrowButton.jsx
- packages/carousel/src/ArrowButton/ArrowButton.styles.js
- packages/carousel/src/Carousel.jsx
- packages/carousel/src/Carousel.spec.js
- packages/carousel/src/Carousel.stories.jsx
- packages/carousel/src/Carousel.styles.js
> added side button option to hide in general and reveal on hover carousel

- common/changes/pcln-design-system/dialog-close-button-bug_2023-11-07-21-25.json
- packages/core/src/Dialog/Dialog.stories.tsx
- packages/core/src/Dialog/Dialog.styled.tsx
> Fix position of Dialog's close button

- README.md
- common/changes/pcln-design-system/fix-UXPT-5817-update-docs_2023-11-15-20-12.json
- packages/core/README.md
update README to point to updated storybook link https://main--5a85e56213417800200978ab.chromatic.com
and remove unused and outdate docs links
> fix(UXPT-5817): update docs

- common/changes/pcln-popover/AIR-59342_2023-11-16-20-32.json
- packages/popover/src/Popover/Popover.stories.jsx
- packages/popover/src/PopoverContent/PopoverContent.jsx
> feat(AIR-59342): add ability to render under certain element

- common/changes/pcln-design-system/bugFix-UXPT-4211-RemoveBgForDisableButtonLink1_2023-11-17-01-11.json
- packages/core/src/Button/Button.spec.tsx
- packages/core/src/Button/Button.tsx
This PR is to revert the !important added in https://github.com/priceline/design-system/pull/1417 and fix the bug other way.
> Bug fix/uxpt 4211 fix important

- common/changes/pcln-design-system/UXPT-3816-radioButtonImprovements_2023-11-21-16-05.json
- packages/core/src/Radio/Radio.stories.tsx
- packages/core/src/Radio/Radio.tsx
- packages/core/src/Radio/__snapshots__/Radio.spec.tsx.snap
[Ticket](https://priceline.atlassian.net/browse/UXPT-3816)
This Pr is to make changes to cursor and default color of the radio button. Made some updates to stories of the radio button as per discussion in last DS meeting.
Before updating story : 
https://github.com/priceline/design-system/assets/119969297/3436b984-5e42-43fb-a342-9cbc9e3a964e
After updating story:
https://github.com/priceline/design-system/assets/119969297/0db45511-7c72-41ba-847c-cc14d5b7d3ad
> Uxpt 3816 radio button improvements

- common/changes/pcln-design-system/AIR-60645_2024-01-26-19-56.json
- packages/core/src/Heading/Heading.stories.tsx
- packages/core/src/stories/Colors.stories.tsx
- packages/core/src/theme/theme.ts
- packages/core/src/utils/createColorScheme.ts
Added color scheme for heading. Also added the display on the color storybook
> Add color scheme for heading text color

- common/changes/pcln-design-system/change-color_2024-02-09-17-52.json
- packages/core/src/Badge/__snapshots__/Badge.spec.tsx.snap
- packages/core/src/Banner/__snapshots__/Banner.spec.tsx.snap
- packages/core/src/RatingBadge/RatingBadge.spec.tsx
- packages/core/src/RatingBadge/__snapshots__/RatingBadge.spec.tsx.snap
- packages/core/src/Stamp/__snapshots__/Stamp.spec.tsx.snap
- packages/core/src/theme/__snapshots__/theme.spec.ts.snap
- packages/core/src/theme/colors.ts
- packages/core/src/utils/createColorStyles.spec.ts
- packages/core/src/utils/createPalette.spec.ts
Change the color orange to color of orange dark
> change color of base orange to dark

- common/changes/pcln-design-system/dialog-header-updates_2024-02-13-15-26.json
- packages/core/src/Dialog/Dialog.stories.tsx
- packages/core/src/Dialog/Dialog.styled.tsx
- packages/core/src/Dialog/Dialog.tsx
- packages/core/src/Toast/Toast.spec.tsx
- packages/core/src/Toast/Toast.tsx
- packages/core/src/ToastProvider/ToastProvider.spec.tsx
* Use `CloseButton` in Dialog
* Change default Dialog header color to `heading`
> Update Dialog close button and header

- common/changes/pcln-design-system/chore-UXPT-3813-update-checkbox-states_2024-02-12-20-49.json
- packages/core/src/Checkbox/Checkbox.stories.tsx
- packages/core/src/Checkbox/Checkbox.tsx
- packages/core/src/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
[UXPT-3813](https://priceline.atlassian.net/browse/UXPT-3813):
* Update unchecked hover state to render svg with `base` with new stories showing colour options
* Show not-allowed cursor when disabled
* Fix vertical alignment on label
* Update focus to focus-visible
* Changelog
> UXPT-3813: update checkbox states

- common/changes/pcln-modal/fix-RC-XXXXX-modal-close-btn_2024-02-27-05-20.json
- packages/modal/src/ModalHeader.jsx
- packages/modal/src/__snapshots__/Headers.spec.js.snap
Fixes alignment bug with close button on modal
**Bug**
**Fix**
> fix(RC-XXXXX): fixes modal close button alignment

- common/changes/pcln-design-system/feat-UXPT-6318-update-ds-for-unified-search_2024-02-27-04-25.json
- common/changes/pcln-popover/feat-UXPT-6318-update-ds-for-unified-search_2024-02-27-15-28.json
- packages/core/src/Button/Button.spec.tsx
- packages/core/src/Button/Button.tsx
- packages/core/src/Dialog/Dialog.stories.tsx
- packages/core/src/Dialog/Dialog.styled.tsx
- packages/core/src/Dialog/Dialog.tsx
- packages/core/src/FormField/__snapshots__/FormField.spec.tsx.snap
- packages/core/src/IconButton/__snapshots__/IconButton.spec.tsx.snap
- packages/core/src/Select/Select.spec.tsx
- packages/core/src/Select/Select.stories.args.ts
- packages/core/src/Select/Select.stories.tsx
- packages/core/src/Select/Select.tsx
- packages/core/src/Select/__snapshots__/Select.spec.tsx.snap
- packages/core/src/Step/__snapshots__/Step.spec.tsx.snap
- packages/core/src/Stepper/__snapshots__/Stepper.spec.tsx.snap
- packages/core/src/index.ts
- packages/popover/src/Popover/__snapshots__/Popover.spec.js.snap
* Button updates
* Focus styles trigger on `:focus-visible` and disabled colour to use `background.tone`
* Select updates
* Truncates long options
* Add subtle variation based on Button
* Dialog updates
* Add `headerContentProps` to allow changes to spacing and grid styles
* Changelog
https://github.com/priceline/design-system/assets/156821810/efbd3d6f-91ab-4fa7-bad5-505d844fe094
> feat: update DS components to match unified search

- common/changes/pcln-design-system/HTL-99330-badge-caption_2024-02-28-22-25.json
- packages/core/src/Badge/Badge.spec.tsx
- packages/core/src/Badge/Badge.stories.args.ts
- packages/core/src/Badge/Badge.stories.tsx
- packages/core/src/Badge/Badge.tsx
- packages/core/src/Badge/__snapshots__/Badge.spec.tsx.snap
> feat(HTL-99330): add caption as text style option

- common/changes/pcln-design-system/dialog-content-wrapper-full-height-if-footer_2024-03-06-18-14.json
- packages/core/src/Dialog/Dialog.styled.tsx
* only full height Dialog content if footer content exists
* only overflow scroll content if footer content exists
> DialogInnerContentWrapper full height if footerContent exists

- common/changes/pcln-design-system/feat-UXPT-6139-drawer-component_2024-02-23-15-49.json
- packages/core/src/Drawer/Drawer.spec.tsx
- packages/core/src/Drawer/Drawer.stories.tsx
- packages/core/src/Drawer/Drawer.styled.tsx
- packages/core/src/Drawer/Drawer.tsx
Storybook: https://5a85e56213417800200978ab-ifcoylgxqo.chromatic.com/?path=/docs/drawer--docs
> feat(UXPT-6139): add drawer component

- common/changes/pcln-design-system/fix-UXPT-6139-export-drawer_2024-04-09-16-46.json
- packages/core/config/jest.config.json
- packages/core/src/Drawer/Drawer.styled.tsx
- packages/core/src/Drawer/Drawer.tsx
- packages/core/src/index.ts
I realized the drawer component was never exported correctly :/
> fix(UXPT-6139): export drawer component

- common/changes/pcln-design-system/chore-RC-26345-shadow-effect-color_2024-05-20-17-29.json
- common/changes/pcln-icons/chore-RC-26345-shadow-effect-color_2024-05-20-17-29.json
- packages/core/src/ShadowEffect/ShadowEffect.tsx
Updates background color for Shadow Effect based on [new design](https://www.figma.com/design/BTdyKP5Vu3feQHY6hIziDR/Unified-Search?node-id=113-41401&t=U723aIekLIhgv1u7-0)
> chore(RC-26345): updates shadow effect color

- common/changes/pcln-design-system/add-disabled-state-to-button-variation-input_2024-06-10-19-29.json
- common/changes/pcln-popover/add-disabled-state-to-button-variation-input_2024-06-10-20-13.json
- packages/core/src/Button/Button.spec.tsx
- packages/core/src/Button/Button.tsx
- packages/core/src/IconButton/__snapshots__/IconButton.spec.tsx.snap
- packages/core/src/Step/__snapshots__/Step.spec.tsx.snap
- packages/core/src/Stepper/__snapshots__/Stepper.spec.tsx.snap
- packages/popover/src/Popover/__snapshots__/Popover.spec.js.snap
I realized that `Button` is missing the disabled state css for its `input` variation.
> Add disabled state css for Button component variation=input

- common/changes/pcln-design-system/popover-refactor_2024-07-17-12-56.json
- common/config/rush/pnpm-lock.yaml
- packages/core/config/jest.config.json
- packages/core/package.json
- packages/core/src/CloseButton/CloseButton.tsx
- packages/core/src/Popover/Overlay.tsx
- packages/core/src/Popover/Popover.stories.args.tsx
- packages/core/src/Popover/Popover.stories.tsx
- packages/core/src/Popover/Popover.styles.tsx
- packages/core/src/Popover/Popover.tsx
- packages/core/src/index.ts
- tools/eslint-config/index.js
This adds a new Popover to the core package with a subset of the props on `pcln-popover`.
> Refactor Popover using Radix UI

- common/changes/pcln-design-system/popover-refactor_2024-07-24-16-20.json
- packages/core/src/Popover/Popover.stories.args.tsx
- packages/core/src/Popover/Popover.stories.tsx
- packages/core/src/Popover/Popover.tsx
This also corrects the prop type expected for `renderContent`.
> Fix close button bug and add max/min width props to Popover

- apps/storybook/package.json
- common/changes/heft-styled-components-plugin/depCleanup_2025-02-11-20-53.json
- common/changes/pcln-autocomplete/depCleanup_2025-02-11-20-53.json
- common/changes/pcln-carousel/depCleanup_2025-02-11-20-53.json
- common/changes/pcln-codemods/depCleanup_2025-02-11-20-53.json
- common/changes/pcln-menu/depCleanup_2025-02-11-20-53.json
- common/changes/pcln-modal/depCleanup_2025-02-11-20-53.json
- common/changes/pcln-popover/depCleanup_2025-02-11-20-53.json
- heft-plugins/heft-styled-components-plugin/package.json
- packages/autocomplete/package.json
- packages/carousel/package.json
- packages/codemods/package.json
- packages/menu/package.json
- packages/modal/package.json
- packages/popover/package.json
- rigs/component/package.json
- tools/babel-preset/package.json
- tools/create-release-notes/package.json
- tools/eslint-config/package.json
- tools/project-change-analyzer/package.json
Moving react-test-renderer to devdependencies.
> moving react-test-renderer to devdep
