priceline/design-system

- package.json
- src/legacyTheme.js
- src/theme.js
Converted the Object.assign usages with usages of the spread operator. This should prevent some issues with IE11 since this will be transpiled by babel
> Removed usage of Object.assign in favor of object spread

- .storybook/Link.js
- src/Link.js
- src/__tests__/__snapshots__/Flex.js.snap
- src/__tests__/__snapshots__/Link.js.snap
The current `Link` implementation doesn't account for different color links. The `:hover` property will get out-of-sync with text color changes.
> Add support for link colors

- docs/Contributing.md
Should add instructions for how to overcome the `ERROR in ./icons.json` when running storybook.
> Add Troubleshooting section in Contributing docs

- src/Button.js
- src/__tests__/__snapshots__/Button.js.snap
- src/__tests__/__snapshots__/GreenButton.js.snap
- src/__tests__/__snapshots__/OutlineButton.js.snap
- src/__tests__/__snapshots__/RedButton.js.snap
Add webkit-font-smoothing to Button component 
- Pull this feature branch
- Run `npm i`
- Run `npm test` - verify no failures
- Run `npm start`
- View [Button component](http://localhost:8000/?selectedKind=Button&selectedStory=Button%20component&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel) in Storybook
- Verify the font-smoothing rule is being applied to buttons
Fixes #102
I submit this fix in support of [Hacktoberfest](https://hacktoberfest.digitalocean.com/). I usually work on our own open source design system, [Vanilla Framework](https://github.com/vanilla-framework/vanilla-framework) 👋🏻
> Add webkit-font-smoothing to Button component

- docs/ThemeProvider.md
- src/ThemeProvider.js
- src/__tests__/ThemeProvider.js
- src/__tests__/__snapshots__/ThemeProvider.js.snap
In order to allow custom breakpoint value overrides per app, this adds a `customBreakpints` prop to the ThemeProvider.
> Add customBreakpoints prop to ThemeProvider - fixes #156

- src/Hide.js
- src/__tests__/__snapshots__/Hide.js.snap
Currently, there is a gap between breakpoints in the Hide component, which means at specific viewport widths, both `xs` and `sm` will be set to `display: none`. Generally, I'd advise against using the Hide component to show different elements *across* breakpoints, but this fix allows you do to so.
> Use fractional max-width values in Hide component - fixes #151

- package.json
- src/Button.js
- src/__tests__/__snapshots__/Button.js.snap
- src/__tests__/__snapshots__/CloseButton.js.snap
- src/__tests__/__snapshots__/GreenButton.js.snap
- src/__tests__/__snapshots__/IconButton.js.snap
- src/__tests__/__snapshots__/OutlineButton.js.snap
- src/__tests__/__snapshots__/RedButton.js.snap
I noticed buttons weren't pulling in Montserrat. Adding `font-family: inherit` seemed to fix it.
> Add font-family: inherit to pull in Montserrat

- .storybook/Banner.js
- docs/Banner.md
- src/Banner.js
- src/__tests__/Banner.js
- src/__tests__/__snapshots__/Banner.js.snap
Wanted to be able to render html / other design system components inside a banner instead of just passing in text. Didn't remove any functionality, only added.
before: `<Banner text='Lorem ipsum' />`
after: `<Banner> **go crazy** </Banner>`
> #163 add children rendering to banner

- src/Button.js
- src/IconButton.js
IconButton: You could not get new icons as it was not passing 'legacy' to the Icon component
Button: If you passed in any padding it would be defined before the default padding - so would not be applied.  
See below where "px:8px" is passed in but the default padding: '0 18px' is lower on stylesheet so will always take precedent.
> Update icon and button

- src/Input.js
- src/InputField.js
- src/Label.js
- src/__tests__/__snapshots__/Input.js.snap
- src/__tests__/__snapshots__/InputField.js.snap
- src/__tests__/__snapshots__/Label.js.snap
I noticed when trying to use an InputField that global `input` styles for margin in a host app were causing the margins to be incorrect. 
So modified the code so that if "showLabel" evaluates to false I set some default margins instead of only applying a margin when it's true.
> bugfix(InputField): add default margins to InputField

- docs/InputField.md
This adds some documentation for how to implement error handling with the InputField and Tooltip components inside the InputField documentation.
> docs(InputField): add example for error handling

- src/Input.js
- src/InputField.js
- src/__tests__/__snapshots__/Input.js.snap
- src/__tests__/__snapshots__/InputField.js.snap
This is a follow-up PR based on the suggestions in https://github.com/pricelinelabs/design-system/pull/218
Replaced the border with a box shadow as @odmin and @msafari suggested
> fix(InputField): Input's border is now a box shadow

- .storybook/Label.js
- docs/Label.md
- src/Label.js
- src/__tests__/Label.js
- src/__tests__/__snapshots__/Button.js.snap
- src/__tests__/__snapshots__/CloseButton.js.snap
- src/__tests__/__snapshots__/GreenButton.js.snap
- src/__tests__/__snapshots__/IconButton.js.snap
- src/__tests__/__snapshots__/Label.js.snap
- src/__tests__/__snapshots__/Link.js.snap
- src/__tests__/__snapshots__/OutlineButton.js.snap
- src/__tests__/__snapshots__/RedButton.js.snap
- `white-space: nowrap` can be useful when used for radios and checkboxes
- The hidden styles aren't great accessibility wise, but better to have a label element than not at all
> Add optional Label styles

- .storybook/Flag.js
- docs/Flag.md
- src/Flag.js
- src/__tests__/Flag.js
- src/__tests__/__snapshots__/Flag.js.snap
problem:
if we passed in hex values directly to Flag, the UI was kinda broken.
fixed:
> fix(Flag): allow hex to be passed in as bg prop

- .storybook/InputField.js
- docs/InputField.md
- src/InputField.js
- src/__tests__/InputField.js
Removes state from the InputField component, negating the need to pass an `onChange` prop. I've added some code to support backwards compatibility with the current API, but would like some input from @byrekt in case I'm missing something about the implementation here
> Use Input value to determine label visibility in InputField

- src/Flag.js
- src/__tests__/__snapshots__/Flag.js.snap
looks like adding the default theme as prop-type messes up the styles. I don't believe this component needs theme as a default prop for unit testing
Styles with default theme were broken:
> fix(Flag): remove theme as default prop for Flag

- src/Button.js
- src/__tests__/Button.js
- src/__tests__/__snapshots__/Button.js.snap
- src/__tests__/__snapshots__/CloseButton.js.snap
- src/__tests__/__snapshots__/GreenButton.js.snap
- src/__tests__/__snapshots__/IconButton.js.snap
- src/__tests__/__snapshots__/OutlineButton.js.snap
- src/__tests__/__snapshots__/RedButton.js.snap
This fixes #285 — I removed set heights and added line-heights and top/bottom padding to the button component. This allows for buttons to wrap to 2 or more lines if needed as well as fixes the line-height issue seen when adding `<a>` to a button component.
> Button with `<a>` styling fix

- docs/Contributing.md
It's not immediately obvious how to make changes to the static site docs. This should make it easier for new people to get started.
> Add contribution instructions for static docs site

- docs/ToggleBadge.md
- src/ToggleBadge.js
- src/__tests__/__snapshots__/ToggleBadge.js.snap
Undo the change for `<ToggleBadge>` to let it change text font-weight on selection. Now it will be bold always.
> Fix toggle font

- docs/.babelrc
- docs/babel.config.js
- docs/package.json
- docs/pages/Icon.md
- docs/src/components.js
Fixes #363 
- Uses the link component from mdx-docs in markdown to correctly handle base path since Next.js does not current support (see https://github.com/zeit/next.js/issues/4998)
- Updates dependencies for docs site
> Fix docs URL basepath

- src/Slider.js
Since we're doing a named import, it's gonna bundle up everything in their `index.js` file in pcln-design-system. 
For example, one of the things that gets bundled up is rc-tooltip which is only used in `createSliderWithTooltip`. But we only need Range looks like. we can reduce the size of rc-slider we're shipping out by just changing this import
> fix(rc-slider): only import range to avoid bundling rc-tooltip

- .gitignore
- package-lock.json
- package.json
When `npm i` with current `master`, there are:
> found 5 moderate severity vulnerabilities
This PR ran `npm audit fix` to pick up to update the vulnerable `codecov` dep.
Fixes #360
> Update codecov dep per npm audit

- package.json
Per [the DEPRECATION NOTE npm PREPUBLISH AND PREPARE doc](https://docs.npmjs.com/misc/scripts#prepublish-and-prepare), it seems to suggest that the favor is on `prepare` over `prepublish`, assuming that backward compatibility to npm 3 is trivial.
Should we update to use `prepare` script?
> chore: Update "prepublish" to "prepare" script

- docs/pages/Text.md
Example for centered text didn't match the actual prop name.
> Update text align example in docs for Text component

- package.json
- packages/autocomplete/package.json
- packages/core/package.json
- packages/icons/package.json
Replace jest `setupTestFrameworkScriptFile` deprecated option with `setupFilesAfterEnv`
fixes #450
> replace jest deprecated option

- package-lock.json
- packages/autocomplete/package-lock.json
- packages/autocomplete/package.json
- packages/autocomplete/src/index.js
- packages/autocomplete/storybook/Autocomplete.js
* Precautious update `ref` instead of ~`innerRef`~ in `MenuCard` to avoid warning of deprecated ~`innerRef`~, when `styled-components` upgrades to v4:
* Uptick `downshift`dep of `Autocomplete` to latest version
* Update upper case of 1st letter (per console warning from the `pcln-design-system` v2 requirement) of the `name` prop for the pin icon in `Autocomplete`.
> Autocomplete Updates

- package-lock.json
- packages/core/src/theme.js
- packages/core/storybook/Colors.js
- packages/core/test/__snapshots__/theme.js.snap
This is a bugfix for #481 and #485 .  lightOrange should not have been aliased as orange, as this could have a serious impact on accessibility and readability. We have decided to bring lightOrange back with a new value of #FEF2E7.
> fix(light-orange): restore lightOrange as fef2e7

- packages/icons/src/Icon.js
`FormField` logic at [L19}(https://github.com/pricelinelabs/design-system/blob/master/packages/core/src/FormField.js#L19) would miss the truthy value by `isIcon` flag to enter the `if` block to run through the logic to render an icon correctly:
https://github.com/pricelinelabs/design-system/blob/2bed46de82d973627283fd6840ec252cd79e6fda/packages/core/src/FormField.js#L19
```jsx
<FormField … >
<Icon … >
…
</FormField>
```
This PR fixes by adding the `isIcon` flag to support `FormField` logic, similar to the [`Icon` in core](https://github.com/pricelinelabs/design-system/blob/master/packages/core/src/Icon.js#L2), which will be deprecated:
https://github.com/pricelinelabs/design-system/blob/2bed46de82d973627283fd6840ec252cd79e6fda/packages/core/src/Icon.js#L2
> fix: add isIcon flag to Icon in pcln-icons to support FormField in core

- packages/core/src/Banner.js
- packages/core/test/__snapshots__/Banner.js.snap
Fix the legacy ~`w`~ to v2 `width` in `Banner`.
https://github.com/pricelinelabs/design-system/blob/162128a7099245e509f47c679a862ae34a22ab07/packages/core/src/Banner.js#L62
Fix the legacy `Heading.h5` style to use `textStyle="display2"` from v2.
https://github.com/pricelinelabs/design-system/blob/162128a7099245e509f47c679a862ae34a22ab07/packages/core/src/Banner.js#L64
> fix: correct width prop in Banner

- packages/core/src/Checkbox.js
- packages/core/src/CloseButton.js
- packages/core/src/Select.js
- packages/core/storybook/Absolute.js
- packages/core/storybook/Flag.js
- packages/core/storybook/FormField.js
- packages/core/storybook/IconButton.js
- packages/core/storybook/IconField.js
- packages/core/storybook/InputGroup.js
- packages/core/storybook/Layouts.js
- packages/core/storybook/Relative.js
- packages/core/storybook/Stamp.js
- packages/core/test/Absolute.js
- packages/core/test/FormField.js
- packages/core/test/IconField.js
- packages/core/test/Relative.js
- packages/icons/test/index.js
Fix the first letter to upper case for all the `Icon` usages in core to kill the undesired console warnings, in sake of improving DX.
> fix: clean up console warnings Icon name's casing

- packages/popover/package.json
Move pcln-design-system from a dependency to a devDependency
It is already defined as a peerDependency
The version of pcln-design-system should be up to the consumer
> fix(popover-dependency): Update dependencies of pcln-popover

- packages/modal/src/Modal.js
- packages/modal/src/ModalHeader.js
- packages/modal/storybook/Modal.js
- packages/modal/test/__snapshots__/Headers.js.snap
This fixes the issue where `tabIndex` is stuck on the close button on the modal and doesn't allow for other tab-able items to be focused. This issue is caused by a `tabIndex="1"`, which prevents other actionable items to be focused, since they all have a `tabIndex="0"` by default.
> fix: Tab index issue prevents focus to be moved around modal

- packages/core/src/IconButton.js
- packages/core/src/IconField.js
- packages/core/storybook/IconField.js
- packages/core/test/IconField.js
- packages/core/test/__snapshots__/IconField.js.snap
Currently, only an Icon is allowed inside a FormField. With these changes, we can also enable the use of an IconButton inside the FormField. 
The IconButton currently gets an outline when it is in focus in the FormField. If the changes from the other PR [https://github.com/pricelinelabs/design-system/pull/540](url) are merged, we will have an option to remove the outline form the IconButton in my understanding.
> Allow Icon Button in Form Field

- packages/modal/README.md
- packages/modal/src/Modal.js
- packages/modal/storybook/Modal.js
- packages/modal/test/Modal.js
- packages/modal/test/__snapshots__/Modal.js.snap
With all the a11y work, there will be some instances of the modal that require different animations and alignment on the page in order to match existing design. This PR adds new props to allow consumers to overwrite animations for both the overlay and the dialog, as well as change the vertical alignment of the dialog on the page.
> feat: add additional props to pcln modal for custom animations

- packages/icons/src/Svg.js
Adding support to icons to use a palette color for `color` and `bg` props.
> Add support for palette colors to icons

- packages/core/test/IconButton.js
- packages/core/test/__snapshots__/Banner.js.snap
- packages/core/test/__snapshots__/Checkbox.js.snap
- packages/core/test/__snapshots__/CloseButton.js.snap
- packages/core/test/__snapshots__/FormField.js.snap
- packages/core/test/__snapshots__/IconButton.js.snap
- packages/core/test/__snapshots__/IconField.js.snap
- packages/core/test/__snapshots__/Radio.js.snap
- packages/core/test/__snapshots__/Select.js.snap
- packages/icons/README.md
- packages/icons/src/Icon.js
- packages/icons/svgr.config.js
- packages/icons/test/__snapshots__/index.js.snap
- packages/icons/test/index.js
According to a11y, icons don’t actually require title/desc unless the icon is meant to be interacted with by the user. We currently handle this correctly by setting aria-hidden to true but these prop type warnings are not consistent with the behaviour.
Additionally, I updated the readme to the new themeable approach which is simply to allow the icon to inherit from the parent component. We currently don't have a way of passing primary or any other semantic name through to the icon but I will be bringing this up as a topic of the next DS meeting.
> Remove Warnings and Update Readme for Theming

- packages/core/package-lock.json
- packages/core/package.json
Updating core to 2.3.1 with pcln-icons 2.1.0, will create a release once merged in.
> Core version 2.3.1 with pcln-icons 2.1.0

- docs/pages/Theming.md
- packages/core/src/Hug.js
- packages/core/src/theme.js
- packages/core/src/utils.js
- packages/core/storybook/Box.js
- packages/core/test/__snapshots__/Flag.js.snap
- packages/core/test/__snapshots__/Hug.js.snap
- packages/core/test/__snapshots__/Radio.js.snap
- packages/core/test/__snapshots__/ThemeProvider.js.snap
- packages/core/test/__snapshots__/theme.js.snap
When `color="text"` is used, `bg` prop is required to support theme. Otherwise, "text" color falls back to use original "text" from original color set.
- update line height standard pellet in theme to 1.4 per @wesleymartin85 
- a new `Box` story - Theme user case: color=text
- "text" color use case in migration guide
```
"text" Color Use Case
- If "text" color is used (i.e. `color="text"`), the `bg` prop is required for
theming. Palette namespace is also suggested to be provided for both `color` &
`bg` props.
<Box mt={3} color="text.lightest" bg="background.dark">
Theme 1: color="text.lightest" value & bg="background.dark"
</Box>
<Box mt={3} color="text" bg="background.lighted">
Theme 2: color="text" & "bg"="background.lighted"
</Box>
```
> refactor: update color theme fn per "text" color & migration guide

- packages/core/package-lock.json
- packages/core/package.json
Fast-track PR to version core at v2.3.2 for next release.
cc prev reviewers involved for the items in this release, @jes708 / @sdalonzo / @achoboter 
Once CI is green, w. admin write, I'd merge the fast-track version PR to publish a release to move forward with the theme patches.
> chore: version core 2.3.2

- packages/core/package.json
- packages/core/src/Select.js
- packages/core/test/__snapshots__/FormField.js.snap
- packages/core/test/__snapshots__/Select.js.snap
The native select arrow on IE11 was covering our custom icon, this change hides the native one. Also changed the rollup command to be run with `npx`, my terminal was not able to find the rollup executable from .bin without `npx`. Using `npx` makes it more reliable.
> fix: Select arrow in IE11

- packages/core/src/Image.js
- packages/core/test/__snapshots__/Image.js.snap
This pr helps to set height attribute precedence
> fix: adding-image-height-attribute-precedence

- packages/core/src/IconButton.js
- packages/core/test/__snapshots__/CloseButton.js.snap
- packages/core/test/__snapshots__/IconButton.js.snap
- packages/core/test/__snapshots__/IconField.js.snap
Fixing issue #594 
- added `color: inherit` to the hover of IconButton
> Fix: IconButton Close Hover - #594

- docs/IconField.md
- docs/pages/Banner.md
- docs/pages/FormField.md
- docs/pages/Icon.md
- docs/pages/IconButton.md
- docs/pages/Layout.md
- docs/pages/Stamp.md
- docs/pages/Theming.md
most of these just clear warnings with the initial capital - the one that was actually broken was in `Layout`, it referred to `hotel` when the icon is called `Hotels`
> fix Icon references in docsite

- packages/icons/src/Icon.js
- packages/icons/test/index.js
Fixes #610 
Plus rearrange to use less default props for html attributes that could be inline in JSX.
> Fix unmapped icon handlement

- packages/icons/src/Icon.js
using a ternary to key off of the name passed in as a prop. tested 3 scenarios: blank string, wrong icon name, no prop at all. all worked and gave the props message.
> Fixed undefined bug on IconName var

- packages/icons/package.json
- version packages/icons for pcln-icons v2.2.2
- no lock file
- next PR will follow up to use pcln-icons v2.2.2 for core and doc site
> Version pcln-icons v2.2.2

- packages/core/src/IconButton.js
- packages/core/test/__snapshots__/CloseButton.js.snap
Props Check was failing because title, titleId, desc and descId were not being passed down into the `Icon` element from the `TransparentButton` element
> Added props to Icon element so the PropType check doesn't complain

- packages/core/src/GreenButton.js
- packages/core/src/OutlineButton.js
- packages/core/test/GreenButton.js
- packages/core/test/OutlineButton.js
- packages/core/test/__snapshots__/GreenButton.js.snap
- packages/core/test/__snapshots__/OutlineButton.js.snap
`GreenButton` and `OutlineButton` were recently switch to functional components which broke any uses of the components when they are nested into another styled-component.
For example:
```.js
const StyledBox = styled(Box)`
${GreenButton} {
background-color: red;
}
`;
```
Currently breaks because `GreenButton` isn't a styled-component. This PR reverts these components back to a styled-component so they can be nested.
> Fix: Reverting GreenButton and OutlineButton to styled-components

- .gitignore
- package-lock.json
- package.json
- packages/autocomplete/package.json
- packages/autocomplete/rollup.config.js
- packages/core/package.json
- packages/modal/package.json
- packages/popover/babel.config.js
- packages/popover/package.json
- packages/slider/package.json
- rollup.config.js
Apply rollup to packages that don't use it yet (coming in an additional PR)
Add `npm run bundle:audit` command
> apply rollup to all packages except icons

- packages/popover/src/Arrow.js
- packages/popover/src/Popover.js
- packages/popover/src/PopoverContent.js
- packages/popover/test/__snapshots__/Popover.js.snap
Closes https://github.com/pricelinelabs/design-system/issues/631
Tests pass, Popover works as expected. See my comment on that issue for more details. Particularly of note: I was never able to reproduce the scroll reset bug.
> Fix broken Popover by changing innerRefs to refs

- MIGRATING_to_v3.md
- packages/autocomplete/test/__snapshots__/index.js.snap
- packages/core/src/Input.js
- packages/core/src/Select.js
- packages/core/src/TextArea.js
- packages/core/src/utils.js
- packages/core/test/__snapshots__/FormField.js.snap
- packages/core/test/__snapshots__/IconField.js.snap
- packages/core/test/__snapshots__/Input.js.snap
- packages/core/test/__snapshots__/Select.js.snap
- packages/core/test/__snapshots__/TextArea.js.snap
Input, TextArea, and Select will now each use `utils/borders` for `borders`, removing inconsistent use of `box-shadow`.
Related to https://github.com/priceline/design-system/issues/529
> Swap Input and TextArea to use border over box-shadow (#529)

- MIGRATING_to_v3.md
- packages/autocomplete/src/index.js
- packages/core/src/Badge.js
- packages/core/src/Banner.js
- packages/core/src/Box.js
- packages/core/src/Flag.js
- packages/core/src/Flex.js
- packages/core/src/RatingBadge.js
- packages/core/src/Stamp.js
- packages/core/src/ToggleBadge.js
- packages/core/src/Tooltip.js
- packages/core/storybook/Flex.js
- packages/modal/src/Modal.js
- packages/modal/src/ModalHeader.js
- packages/modal/src/SmallModalHeader.js
- packages/popover/src/Arrow.js
- packages/popover/src/Popover.js
- packages/popover/src/PopoverContent.js
Marking the `bg` prop as deprecated in favor of `color`.
Addresses https://github.com/priceline/design-system/issues/650
> (#650) Mark bg prop as deprecated

- packages/core/src/FormField.js
- packages/core/test/__snapshots__/FormField.js.snap
> fix(label-width): prevent label width overflow

- packages/core/src/Link.js
- packages/core/test/Link.js
- packages/core/test/__snapshots__/BlockLink.js.snap
- packages/core/test/__snapshots__/Breadcrumbs.js.snap
- packages/core/test/__snapshots__/Link.js.snap
Wanted to make it easier to ensure safe cross-origin navigation using the Link component.
- Added conditional `rel` value `noopener` when `target='_blank'`
- Added new test to assert value is added
- Update snapshots
Sources for reading more about this topic and specific attribute value:
- https://mathiasbynens.github.io/rel-noopener/
- https://developers.google.com/web/tools/lighthouse/audits/noopener
> Link - set rel noopener when target is blank

- packages/core/test/Banner.js
- packages/core/test/Flex.js
Removes some skipped tests that are no longer needed due to using a more composed API for Banner. Additionally, fixes a skipped block in Flex.
> Resolve skipped tests

- .travis.yml
- package-lock.json
- packages/core/src/index.js
- packages/modal/package.json
- packages/popover/package.json
- Adds an export to core to allow compatibility with pcln-modal v3
- Makes react-popper a peerDependency to alleviate publishing error
- Uses latest @reach/dialog in pcln-modal
> Update @reach/dialog in pcln-modal for DS v2

- packages/modal/package.json
This will allow the host app to specify which versions of dependencies it would like to use, for modal and popover components.
> Update @reach/dialog in pcln-modal

- packages/modal/src/Modal.js
This addresses a couple browser specific bugs.
1. Changes overflow to auto instead of scroll, so IE11 won't always show a scroll bar.
2. Adds relative position and height 100% to prevent an edge case in Firefox where a percentage height of the modal could be ignored
> fix(browser-modal): fix browser specific bugs

- packages/modal/src/ModalHeader.js
Replace direct color usage with palette color for the modal header close button to align with the theme.
> modal header close button focus uses palette color

- docs/package-lock.json
- docs/package.json
- docs/pages/_app.js
- docs/pages/_document.js
- docs/pages/index.md
Noticed 2 security vulnerabilities recommendations from Github. The 2 modules to upgrade are `acorn` and `minimist` and they both target the docs website. I initiated 2 automatic PRs for them: 
- acorn: #725
- minimist: didn’t want to create an automated PR, as it seems like one of the docs dependencies I quote from the error message “require a version that is incompatible with the update.”
Turned out that the version of next.js in docs version is behind. This PR upgrade the docs next.js to v9.3.1 as well as apply the required deprecation fixes.
This PR should address the `minimist` upgrade and will still need to have a separate PR for `acorn` as the minimum version on this PR is `6.1.1` and required version is `>=6.4.1` (addressed in #725). 
I have tested the static build locally.
> Update the docs site next.js version to 9.3.1

- packages/modal/src/ModalHeader.js
- packages/modal/test/__snapshots__/Headers.js.snap
Noticed this when installing `pcln-modal` in a host app using `styled-components@4` and `design-system@2`.
Before:
After:
Tested in Storybook
> Fix style bug in ModalHeader

- packages/core/package.json
The latest published version of `pcln-design-system` is `3.2.0`, but the version bump was never committed.
> Bump core version to reflect latest published version

- packages/core/src/Checkbox.js
- packages/core/test/__snapshots__/Checkbox.js.snap
Found an issue where the hover color of the checkbox was not respecting the given color based on the theme.
Before:
After:
> Change checkbox hover color to dark rather than dark blue

- packages/modal/README.md
- packages/modal/src/Modal.js
- packages/modal/storybook/Modal.js
Closes #757 
Tested and confirmed that the timeout on the Transition component was causing the open delay.
> Modal Timeout Prop

- packages/core/package.json
Draft release: https://github.com/priceline/design-system/releases/tag/untagged-3efad8f6527c67467436
> Bump core to 3.4.0

- packages/core/package.json
- packages/core/src/utils.js
Apps using SSR were getting `Element is undefined` errors because we were using `Element` from DOM, which DNE in a Node environment. This makes that prop type more permissive and no longer uses `Element`.
> Fix ref prop type ssr

- packages/popover/src/Arrow.js
- packages/popover/src/Popover.js
- packages/popover/src/PopoverContent.js
- packages/popover/storybook/Popover.js
- packages/popover/test/__snapshots__/Popover.js.snap
- Remove all instances of hardcoded popover theme
- Remove prop `bg`/`background` from being passed into styles for `Arrow` and other inner components
- Substitute instances of `bg`/`background` with `color`
- Allow for specifying `borderColor` but will default to `border.base` if none is provided
- Added storybook example of theme colored Popovers
- Updated snapshots
Closes #721
> fix(721): Remove hardcoded popover theme

- packages/core/package.json
In order to quickly identify bugs in the type declarations, I'd like to enable the type declarations so I can gather feedback as a few people work in the core project.
> Enable types for core project

- package-lock.json
- packages/core/package.json
- packages/types/package.json
- packages/types/types/index.d.ts
- packages/types/types/test.tsx
Now uses the correct version of `@types/styled-system`, which prevents confusion because it has the correct props for components.
This PR also adds prop types for layout components. Resolves #792.
> Use version of @types to match styled-system

- packages/core/src/Flag/Flag.js
- packages/core/src/Flag/Flag.stories.js
The right side of the flag already adds an illusion of extra padding which is why the original only had `py` and `pl`. I made both of these props and added `pr` separately (instead of `px`, for this reason).
> add custom padding to flag (#259)

- packages/types/types/index.d.ts
- packages/types/types/test.tsx
- Add types for `Icon` and components using `Icon`
- Adding types for `IconButton` required types for `Button`, so did that and `CloseButton`
Closes #789 
Closes #794
> Define prop types for icon & buttons

- .storybook/manager.js
- .storybook/pclnTheme.js
> Add Priceline logo to theme

- MIGRATING_to_v3.md
- codemods/icons-v2-to-v3/README.md
- codemods/icons-v2-to-v3/iconsV2toV3.js
This codemod can be run via `jscodeshift`. It is intended to replace imports from `pcln-icons/lib` with named imports from `pcln-icons`.
Resolves #859
> Create codemod to assist with pcln-icons upgrade

- docs/package-lock.json
- githooks/no-internal-registry.js
- package.json
I decided to go with a pre-commit hook since husky doesn't support prepublishOnly. It also makes sense to just ensure that no bad lockfiles are committed, since you shouldn't publish if your lockfiles (or any other files) differ from master anyway.
Resolves #856.
> Add pre-commit hook to screen for internal URLs in lockfiles

- packages/core/package.json
We've encountered issues with existing TSC builds failing due to improper usage of various props from before type declarations were available. Since this was a breaking change, we've elected to roll back the `types` field in the core package. We'll re-introduce typings with instructions to opt-in as part of a future release.
> Remove types field from core package to avoid breaking TSC builds

- docs/pages/_document.js
Adding lang='en-US' attribute to html tag for Accessibility.
> Add lang attribute to html tag for Accessibility

- .gitignore
- package-lock.json
- packages/core/package.json
- packages/core/src/utils/getSCMigrationRef/getSCMigrationRef.js
- packages/core/src/utils/getSCMigrationRef/getSCMigrationRef.sc3.spec.js
- packages/core/src/utils/getSCMigrationRef/getSCMigrationRef.sc4.spec.js
This change was prompted by the warnings generated at runtime by any component that uses `getSCMigrationRef`. The cause of this was that the way we were previously detecting the `styled-components` version had the warning built into the getter for the `.extend` property. This fix should behave the same, but instead relies on the presence of the `injectGlobal` export that was removed in v4.
> Change how we detect Styled Components version

- docs/pages/Banner.md
- docs/pages/CloseButton.md
- docs/pages/FormField.md
- docs/pages/Hug.md
- docs/pages/Icon.md
- docs/pages/IconButton.md
- docs/pages/IconField.md
- docs/pages/Stamp.md
- docs/pages/Theming.md
- docs/src/components.js
- docs/src/navigation.js
- Add named icon imports into `components.js` for use throughout doc examples
- Replace all `<Icon name='x' />` components except for iconography (update coming later)
- Update props for `IconButton` docs, fix typos, add more examples
- Move `IconField.md` doc into `/pages` and add to navigation
> Update named icons and IconButton docs

- packages/core/src/Absolute/Absolute.spec.js
- packages/core/src/Badge/Badge.spec.js
- packages/core/src/Banner/Banner.spec.js
- packages/core/src/Box/Box.spec.js
- packages/core/src/Box/__snapshots__/Box.spec.js.snap
- packages/core/src/Button/Button.spec.js
- packages/core/src/Checkbox/Checkbox.spec.js
- packages/core/src/Flag/Flag.spec.js
- packages/core/src/Flex/Flex.spec.js
- packages/core/src/FormField/FormField.spec.js
- packages/core/src/FormField/__snapshots__/FormField.spec.js.snap
- packages/core/src/RatingBadge/RatingBadge.spec.js
- packages/core/src/Stamp/Stamp.spec.js
- packages/core/src/Text/Text.spec.js
- packages/core/src/ToggleBadge/ToggleBadge.spec.js
- packages/core/src/Tooltip/Tooltip.spec.js
- packages/core/src/Tooltip/__snapshots__/Tooltip.spec.js.snap
- Refactor tests to remove all deprecated proptype warnings from tests
- Change mock pattern for tests explicitly asserting `console.error` calls and messages
- Add components or properties where missing in tests
- `FormField` uses `Input` which requires an `id` prop set, also uses `Select` which requires a `Label`
- `Checkbox` requires an `onChange` prop which was missing from one test
- Refactor `Box` and `Tooltip` to remove deprecated prop type use from normal tests and move into deprecated prop type test suite like other existing tests
- Couldn't do this for components that mark `bg` as deprecated but have not yet removed the requirement of `bg` to render the component correctly (includes `Badge`, `Banner`, `Flag`, `RatingBadge`, `Stamp`, `ToggleBadge`) so I added the `console.error` …
> Issue(845): Remove deprecated prop type warnings from tests

- packages/autocomplete/package.json
- packages/autocomplete/storybook/Autocomplete.stories.js
- packages/core/src/Absolute/Absolute.stories.js
- packages/core/src/Flag/Flag.stories.js
- packages/core/src/FormField/FormField.spec.js
- packages/core/src/FormField/FormField.stories.js
- packages/core/src/FormField/__snapshots__/FormField.spec.js.snap
- packages/core/src/Icon/Icon.stories.js
- packages/core/src/Relative/Relative.spec.js
- packages/core/src/Relative/Relative.stories.js
- packages/core/src/Stamp/Stamp.stories.js
- packages/core/src/stories/Layouts.stories.js
- packages/icons/test/index.js
- packages/popover/package.json
- packages/popover/src/Overlay/Overlay.spec.js
- packages/popover/src/Popover/Popover.spec.js
- packages/popover/src/Popover/Popover.stories.js
- packages/popover/src/PopoverContent/PopoverContent.spec.js
- Replace all tests and stories usage of `<Icon />` with named icons
- Add console.error mocks to popover tests to remove warnings about `StyledOverlay` (`Box`) `bg` prop use
- Update stories to use palette colours
Duplicate of #915 to try and kickoff CI
> Update all tests and stories to use named icons

- .github/workflows/on-master.yml
This change should fix the 404s that are breaking the static docsite
> Update docsite action to create .nojekyll file

- packages/core/src/CloseButton/__snapshots__/CloseButton.spec.js.snap
- packages/core/src/IconButton/IconButton.js
- packages/core/src/IconButton/IconButton.spec.js
- packages/core/src/IconButton/IconButton.stories.js
- packages/core/src/IconButton/__snapshots__/IconButton.spec.js.snap
- packages/core/src/IconField/__snapshots__/IconField.spec.js.snap
- packages/modal/src/__snapshots__/Headers.spec.js.snap
- Remove default background colour from disabled class inherited on button
- Add story and test for disabled state example
- Refactor IconButton tests to use named icons
https://5a85e56213417800200978ab-zgbehvvzqn.chromatic.com/?path=/story/iconbutton--with-disabled
Closes #939
> fix(939): IconButton background colour transparent when disabled

- common/changes/pcln-design-system/revert-button-style-fix_2020-10-21-14-57.json
- packages/core/src/Button/Button.js
We didn't realize that this change broke refs for Button, so reverting it will enable us to release subsequent versions between `3.6.1` and `4.0`.
Original PR:
https://github.com/priceline/design-system/pull/928
> Revert change to remove mapProps from Button

- common/changes/pcln-design-system/dgiraldo313-patch-1_2020-10-21-14-40.json
- packages/core/src/Divider/Divider.js
- packages/core/src/Divider/__snapshots__/Divider.spec.js.snap
> Add background color fallback, so that browser color is not applied when screen is zoomed in to >125%

- common/changes/pcln-design-system/stamp-line-height-update_2020-11-06-17-27.json
- packages/core/src/Badge/Badge.js
- packages/core/src/Badge/__snapshots__/Badge.spec.js.snap
- packages/core/src/Stamp/Stamp.js
- packages/core/src/Stamp/__snapshots__/Stamp.spec.js.snap
As per Wes, the 'small' size for Stamp and Badge should have a line height of 20px
Patch change file created
[Storybook](https://5a85e56213417800200978ab-vlzhlbalka.chromatic.com/?path=/story/*)
> small size should have a line height of 20px

- common/changes/pcln-popover/popover-bugfix_2020-11-06-20-33.json
- packages/popover/package.json
- packages/popover/src/Popover/__snapshots__/Popover.spec.js.snap
- packages/popover/src/PopoverContent/PopoverContent.js
- packages/popover/src/PopoverContent/PopoverContent.spec.js
> Fix style bug in popover

- .github/workflows/release-branch.yaml
- .gitignore
- common/changes/pcln-autocomplete/automate-release-notes_2020-10-23-16-38.json
- common/changes/pcln-modal/automate-release-notes_2020-10-23-16-38.json
- common/changes/pcln-popover/automate-release-notes_2020-10-23-16-38.json
- common/changes/pcln-slider/automate-release-notes_2020-10-23-16-38.json
- common/config/rush/command-line.json
- common/config/rush/pnpm-lock.yaml
- rush.json
- tools/create-release-notes/.eslintignore
- tools/create-release-notes/.eslintrc.js
- tools/create-release-notes/package.json
- tools/create-release-notes/src/actions/createReleaseNotes.ts
- tools/create-release-notes/src/cli/releaseNotes.ts
- tools/create-release-notes/src/index.ts
- tools/create-release-notes/src/types/Release.ts
- tools/create-release-notes/tsconfig.json
This will deploy a new version to NPM and create a new release on GitHub for the core package whenever a tag like `v.*.*.*` is pushed.
Example: https://github.com/priceline/design-system/releases/tag/v3.6.3
**TODO**
> Automate release notes

- apps/docs/package.json
- apps/storybook/package.json
- common/changes/pcln-popover/fix-button-aria-label_2020-12-04-19-34.json
- packages/autocomplete/package.json
- packages/core/CHANGELOG.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/Button/Button.js
- packages/core/src/Button/Button.spec.js
- packages/core/src/IconButton/IconButton.stories.js
- packages/menu/package.json
- packages/modal/package.json
- packages/popover/package.json
- packages/popover/src/Popover/__snapshots__/Popover.spec.js.snap
- packages/slider/package.json
- tools/types/package.json
This was an unintended regression in DS4. Both the `title` and `aria-label` props will now set the `aria-label` on the rendered `<button>` (`aria-label` prop takes precedence).
> Fix bug when passing aria-label to Button and related components

- common/changes/pcln-design-system/840-rating-badge-bug_2020-12-29-15-51.json
- common/changes/pcln-modal/840-rating-badge-bug_2020-12-29-15-51.json
- packages/core/src/RatingBadge/RatingBadge.js
- packages/core/src/RatingBadge/RatingBadge.spec.js
- packages/core/src/RatingBadge/RatingBadge.stories.js
- packages/core/src/RatingBadge/__snapshots__/RatingBadge.spec.js.snap
- packages/core/src/ShadowEffect/ShadowEffect.spec.js
> Fix bug when using RatingBadge without bg prop

- common/changes/pcln-design-system/update-text-extension-display-names_2020-12-29-20-56.json
- packages/core/src/Text/Text.js
Changing the text display names for the extended components (span, s, p) to be the same as the component name.
> Update Text Extension Display Names

- apps/docs/pages/Banner.md
- apps/docs/pages/GenericBanner.md
- apps/docs/src/components.js
- apps/docs/src/navigation.js
The actual issue was that `<button>` and `<a>` weren't wrapped in back-ticks, so MDX thought they were code. I also reformatted the props table because it included a bunch of empty lines. The rest is just cleanup. I also added `GenericBanner` to the side-nav.
> Fix syntax on GenericBanner page that broke docsite build

- common/changes/pcln-autocomplete/fix-create-release-notes_2021-01-12-15-47.json
- common/changes/pcln-design-system/fix-create-release-notes_2021-01-12-15-47.json
- common/changes/pcln-icons/fix-create-release-notes_2021-01-12-15-47.json
- common/changes/pcln-menu/fix-create-release-notes_2021-01-12-15-47.json
- common/changes/pcln-modal/fix-create-release-notes_2021-01-12-15-47.json
- common/changes/pcln-popover/fix-create-release-notes_2021-01-12-15-47.json
- common/changes/pcln-slider/fix-create-release-notes_2021-01-12-15-47.json
- common/config/rush/command-line.json
- packages/autocomplete/package.json
- packages/core/package.json
- packages/icons/package.json
- packages/menu/package.json
- packages/modal/package.json
- packages/popover/package.json
- packages/slider/package.json
I noticed that the GH Action that creates release notes failed because `ts-node` was missing. This change should make it more reliable.
This PR also includes alphabetized dependencies from the latest `rush publish`.
> Fix create-release-notes command

- common/changes/pcln-design-system/generic-banner-fix_2021-02-08-17-16.json
- packages/core/src/GenericBanner/GenericBanner.js
- packages/core/src/GenericBanner/GenericBanner.spec.js
- packages/core/src/GenericBanner/GenericBanner.stories.js
In GenericBanner:
- allow the heading size to be different than the rest of the text fontSize
-Move the check for the ctaText prop into a better spot so an empty Button or Link doesn't render
> add check for ctaText

- apps/docs/pages/Link.md
Just noticed the docs for Link did not include a reference for the `variation` prop.
> Update Link docs to include variation prop

- common/changes/pcln-design-system/ratingbadge-default-color_2021-02-17-15-18.json
- packages/core/src/RatingBadge/RatingBadge.js
- packages/core/src/RatingBadge/__snapshots__/RatingBadge.spec.js.snap
This broke inadvertently as a result of https://github.com/priceline/design-system/pull/998.
> Fix incorrect default color of RatingBadge

- common/changes/pcln-autocomplete/ratingbadge-color-fix_2021-02-19-18-20.json
- common/changes/pcln-design-system/ratingbadge-color-fix_2021-02-19-18-20.json
- common/changes/pcln-icons/ratingbadge-color-fix_2021-02-19-18-20.json
- common/changes/pcln-menu/ratingbadge-color-fix_2021-02-19-18-20.json
- common/changes/pcln-modal/ratingbadge-color-fix_2021-02-19-18-20.json
- common/changes/pcln-popover/ratingbadge-color-fix_2021-02-19-18-20.json
- common/changes/pcln-slider/ratingbadge-color-fix_2021-02-19-18-20.json
- packages/core/src/RatingBadge/RatingBadge.js
- packages/core/src/RatingBadge/RatingBadge.spec.js
- packages/core/src/RatingBadge/RatingBadge.stories.js
- packages/core/src/RatingBadge/__snapshots__/RatingBadge.spec.js.snap
We noticed inconsistent behavior when combining the deprecated `bg` prop with `color`.
> Fix backward compatibility issue in RatingBadge

- packages/popover/CHANGELOG.json
- packages/popover/CHANGELOG.md
- packages/popover/package.json
- packages/popover/src/Popover/Popover.js
- packages/popover/src/Popover/Popover.stories.js
- packages/popover/src/PopoverContent/PopoverContent.js
- packages/popover/src/PopoverContent/PopoverContent.spec.js
Added new optional prop hideOverlay to Popover component - so that when opened, popover has the option to not be closed by clicking on overlay (e.g. only by clicking on X (close) button inside popover content.
> feat(RC-17925): hide popover overlay

- .github/workflows/continuous-integration.yml
This will create a storybook in Chromatic even if one CI job fails
> Don't fail other jobs if one CI job fails

- common/changes/pcln-design-system/UXPT-1162-password-input-component_2021-03-09-21-58.json
- packages/core/src/Input/Input.js
- packages/core/src/Input/Input.stories.js
- packages/core/src/PasswordInput/PasswordInput.js
- packages/core/src/PasswordInput/PasswordInput.spec.js
- packages/core/src/PasswordInput/PasswordInput.stories.js
- packages/core/src/PasswordInput/index.js
A password input component with a visibility option and regex checks.
https://priceline.atlassian.net/browse/UXPT-1162
Basic:
With a regex check progress bar:
Mobile:
> Uxpt/1162: password input component

- common/changes/pcln-design-system/fix-default-props-blown-away-icon-field_2021-03-18-18-04.json
- packages/core/src/FormField/__snapshots__/FormField.spec.js.snap
- packages/core/src/IconField/IconField.js
false was a valid value which prevented the default prop value from working 🤦
> Fix default props blown away icon field

- common/changes/pcln-design-system/update-default-password-requirements_2021-03-22-16-44.json
- packages/core/src/PasswordInput/PasswordInput.js
This update bring parity to the default requirements for Priceline users which is nice + 12 characters is between than 8.
> Update default password requirements

- common/changes/pcln-design-system/improve-text-extensions_2021-04-15-19-26.json
- packages/core/src/Banner/__snapshots__/Banner.spec.js.snap
- packages/core/src/Text/Text.js
For some reason this is breaking CI for my other PR: https://github.com/priceline/design-system/pull/1063 
Simple change that I quite like anyway, simplifies the implementation of Strikethrough and our other Text extensions.
Nothing actually changes here functionally, purely code quality.
> Improve Text Extensions

- common/changes/pcln-design-system/password-input-valid-without-progress-bar_2021-04-13-00-41.json
- packages/core/src/PasswordInput/PasswordInput.js
- packages/core/src/PasswordInput/PasswordInput.spec.js
- packages/core/src/PasswordInput/PasswordInput.stories.js
- packages/core/src/ProgressBar/ProgressBar.stories.js
* Added the isValid prop
* Start the progress bar empty instead of at step one
* Added a password update form example to the storybook
* Added an empty progress bar example to the storybook
* Added an id prop for connecting the label to the input
* Changed regex prop type from string to regex
> PasswordInput is valid without progress bar

- common/changes/pcln-menu/fix-pcln-menu-use-theme-font_2021-12-20-21-47.json
- packages/menu/src/MenuList/MenuList.js
- packages/menu/src/MenuList/MenuList.spec.js
- Use hardcoded font only if no font detected from theme context
- Add tests for both conditions
> fix(): Allow for menu list font to be inherited

- apps/docs/.eslintrc.js
- apps/docs/.eslintrc.json
- apps/docs/babel.config.js
- apps/docs/next.config.js
- apps/docs/package.json
- apps/docs/pages/_app.js
- apps/docs/pages/_document.js
- common/config/rush/pnpm-lock.yaml
This upgrade fixes a postinstall script that was breaking in Node 16 for an old version of `@ampproject/toolbox-optimizer`.
Failure: https://github.com/priceline/design-system/runs/4705427098?check_suite_focus=true
Successful run on this branch: https://github.com/priceline/design-system/runs/4705780733?check_suite_focus=true
> Upgrade next.js in docs project to fix broken postinstall

- common/changes/pcln-menu/chore-HTL-77781-menulist-overflow-auto_2022-01-28-18-38.json
- packages/menu/src/MenuList/MenuList.js
The Menu component current shows scrollbars all the time on Windows browsers.
Ideal behavior would be to only appear when needed, as seen on OSX.
Updating the overflow-y style in MenuList to 'auto' rather than 'scroll' to accomplish this.
> Update MenuList overflow to auto

- tools/create-release-notes/src/actions/createReleaseNotes.ts
The same info is already included in our GH releases. This should make release previews on Slack look nicer.
> Remove duplicate info from release notes markdown

- CONTRIBUTING.md
- common/changes/pcln-design-system/button-chip-accessibility_2022-02-16-14-45.json
- common/changes/pcln-popover/button-chip-accessibility_2022-02-16-14-45.json
- packages/core/src/Chip/ButtonChip/ButtonChip.spec.tsx
- packages/core/src/Chip/ButtonChip/ButtonChip.tsx
- packages/popover/src/Popover/Popover.stories.js
- packages/popover/src/Popover/__snapshots__/Popover.spec.js.snap
- packages/popover/src/PopoverContent/PopoverContent.js
This PR addresses this [ticket](https://priceline.atlassian.net/browse/UXPT-2517)
Before:
After:
ALSO: Fixed tab-index/focus-trap issue for PopoverContent, see relevant Popover Story (titled "Filter Chips")
> Update focus styling for ButtonChip

- common/changes/pcln-design-system/buttonchip-focus-styling_2022-02-23-16-22.json
- packages/core/src/Chip/ButtonChip/ButtonChip.spec.tsx
- packages/core/src/Chip/ButtonChip/ButtonChip.tsx
- packages/core/src/Chip/ChipLabel/index.tsx
The floating outer-border effect that is applied when a ~~Button~~Chip is focused now utilizes `outline` css styling, instead of `box-shadow`
Edit: now applies to all Chips (ButtonChip, FilterChip, and ChoiceChip), not just ButtonChip
> change ButtonChip focus styling to use outline

- common/changes/pcln-carousel/carousel-click-handlers_2022-03-17-18-44.json
- packages/carousel/src/Carousel.js
- packages/carousel/src/Carousel.spec.js
- packages/carousel/src/Carousel.stories.js
This enables consumers to react to the current slide changing, either from clicking next/prev, scrolling, or using the dots.
> Add handler to Carousel when current slide changes

- .gitignore
- common/changes/pcln-design-system/layout-z-index_2022-03-28-14-46.json
- packages/core/src/Card/Card.stories.tsx
- packages/core/src/Layout/Layout.stories.tsx
- packages/core/src/Layout/Layout.tsx
This is useful if you need children to overlap.
> Pass zIndex prop to Layout children wrappers

- common/changes/pcln-design-system/update-form-field-to-accept-props_2022-04-01-22-35.json
- packages/core/src/FormField/FormField.tsx
- packages/core/src/FormField/__snapshots__/FormField.spec.tsx.snap
@pcln-brianna and I are trying to set the width prop on FormField but cannot, same goes for any other style overrule.
This will not have changes for people upgrading to the new version unless they were setting the props on FormField and expecting them to work but they weren't.
> Update form field to accept props

- common/changes/pcln-design-system/filterchiip-add-name-prop_2022-04-08-14-01.json
- packages/core/src/Chip/FilterChip/FilterChip.spec.tsx
- packages/core/src/Chip/FilterChip/FilterChip.stories.tsx
- packages/core/src/Chip/FilterChip/FilterChip.tsx
Fixes #[1148](https://github.com/priceline/design-system/issues/1148) | Added mandatory name prop to FilterChip component.
> Fixes #1148 | Added mandatory name prop to FilterChip component.

- common/changes/pcln-design-system/fix-theme-wrapper_2022-03-29-19-50.json
- packages/core/src/ThemeProvider/ThemeProvider.tsx
- packages/core/src/utils/createTheme.ts
Our current ThemeProvider does not take into account existing themes, so whenever an inner ThemeWrapper is invoked the existing styles created by the outer provider are ignored and the new theme is merged with the `defaultTheme` from DS.
Changing the signature of the theme prop from an object to a function allows us to retrieve the existing theme and merge it against the new theme. This follows the approach suggested by the Styled Components docs https://styled-components.com/docs/advanced#function-themes
> fix DS theme provider to account for existing provider

- common/changes/pcln-carousel/carousel-arrowButton-fix_2022-05-26-18-04.json
- packages/carousel/src/ArrowButton/ArrowButton.styles.js
> fix missing semicolon on ArrowButton styling

- common/changes/pcln-popover/feature-popover-styling_2022-06-02-18-56.json
- packages/popover/src/Popover/Popover.js
- packages/popover/src/Popover/__snapshots__/Popover.spec.js.snap
Adding additional functionality to `pcln-popover`:
- A `display` CSS override to help when the default `display: inline-block` causes styling issues in some contexts.
- A `toggleIsOpenOnClick` prop to disable the default onClick behavior in the case that Popover is triggered via hover events.
> update popover to allow display styling and disabling onClick

- common/changes/pcln-carousel/feature-add-events-carousel-slide_2022-06-03-20-40.json
- common/changes/pcln-popover/feature-add-events-carousel-slide_2022-06-06-15-43.json
- packages/carousel/src/Carousel.js
- packages/carousel/src/Carousel.spec.js
- packages/carousel/src/Carousel.stories.js
- packages/popover/src/Popover/Popover.js
Add 2 event handler props for `Carousel`: `onSlideClick` and `onSlideKeyDown`. These are passed to the `Carousel` component and will be called for each carousel item.
Add a `stopPropagation` prop to `Popover` allowing an override when Popover causes issues with swallowing events that need to bubble up higher, like in a Carousel for example.
> add onClick and onKeyDown handlers to Carousel children

- common/changes/pcln-design-system/feat-indeterminate-checkbox_2022-07-06-12-49.json
- packages/core/src/Checkbox/Checkbox.spec.tsx
- packages/core/src/Checkbox/Checkbox.stories.tsx
- packages/core/src/Checkbox/Checkbox.tsx
- packages/core/src/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
This adds support for the very legitimate indeterminate checkbox state.
`indeterminate` can only be set via javascript (you can't do something like `<input type='checkbox' indeterminate />`. It just won't work. 
Here is an example below (from the storybook story):
I made it so that it works by passing `indeterminate` as a prop, but it also has support for you to set `indeterminate` via the ref and the styling should apply correctly as well.
> feat(indeterminate-checkbox): add support for indeterminate checkboxes

- common/changes/pcln-carousel/fix-carousel-button-position_2022-08-03-15-51.json
- packages/carousel/src/Carousel.stories.js
- packages/carousel/src/layoutToFlexWidths.js
- packages/carousel/src/layoutToFlexWidths.spec.js
This PR fixes a bug in the width calculation for `Carousel`'s 33-33-33 layout that caused some slides to appear cut off after clicking the `next` button.
> Fix bug in 33-33-33 Carousel layout

- .github/workflows/npm-publish-beta.yaml
From the Rush docs:
Removing that flag prevents the changes to `package.json` from being committed back to the branch.
> Remove --target-branch flag from NPM beta publish workflow

- common/changes/pcln-carousel/fix-carousel-slide-height_2022-08-03-18-54.json
- packages/carousel/src/Carousel.js
This fixes a bug where `Carousel` slides whose contents of have dynamic heights don't fill the whole vertical space available, which can result in slides having different heights.
> Make height of each Carousel slide 100%

- packages/menu/src/Menu/Menu.stories.js
Bri wanted to use the Menu component to create a header link dropdown, we played around with a few ideas and this is one example of how you might do that.
Video demonstrates using "tab" and arrow keys
https://user-images.githubusercontent.com/62619213/182922592-cee6bf32-9ba1-4556-a98d-89f747f89f08.mov
> Create Menu link-dropdown storybook example

- common/changes/pcln-popover/fix-popover-scroll-jumps_2022-08-08-20-28.json
- packages/popover/src/PopoverContent/PopoverContent.js
People have reported an issue where opening the popover below the fold will bounce back up to the top of the screen. Adding `preventScroll` to the `FocusLock` resolves this issue.
> Fix popover scroll jumps

- .github/workflows/npm-publish.yaml
- .github/workflows/release-branch.yaml
- common/config/rush/command-line.json
- common/config/rush/pnpm-lock.yaml
- packages/core/README.md
- rush.json
- tools/create-release-notes/package.json
- tools/create-release-notes/src/actions/createReleaseNotes.ts
- tools/project-change-analyzer/.eslintignore
- tools/project-change-analyzer/.eslintrc.js
- tools/project-change-analyzer/.npmignore
- tools/project-change-analyzer/package.json
- tools/project-change-analyzer/src/getAppReleaseMetadata/getAppReleaseMetadata.ts
- tools/project-change-analyzer/src/getAppReleaseMetadata/index.ts
- tools/project-change-analyzer/src/getChangedProjects/getChangedProjects.ts
- tools/project-change-analyzer/src/getChangedProjects/index.ts
- tools/project-change-analyzer/src/index.ts
- tools/project-change-analyzer/src/setActionOutput/index.ts
- tools/project-change-analyzer/src/setActionOutput/setActionOutput.ts
- tools/project-change-analyzer/tsconfig.json
**Example of a successful run:**
* https://github.com/priceline/design-system/actions/runs/2827555231
* https://github.com/priceline/design-system/runs/7752975485?check_suite_focus=true
> Automatically create GH releases after NPM publish

- common/changes/pcln-carousel/bug-moize-profile-name_2022-08-10-19-58.json
- common/changes/pcln-design-system/bug-moize-profile-name_2022-08-10-19-58.json
- common/config/rush/pnpm-lock.yaml
- packages/carousel/package.json
- packages/carousel/src/helpers.js
- packages/core/src/Layout/Layout.tsx
If the `moize` [profileName](https://github.com/planttheidea/moize#profilename) option is not set, it will create a stack trace and retrieve a default from there.  This has performance implications.  If a profileName is passed as an option, it is used instead.
Contrary to the docs, the profileName option is used regardless of whether stats are collected.
For ref:  https://github.com/planttheidea/moize/blob/master/src/stats.ts#L95
> Fix moize perf issue determining default profile name

- common/changes/pcln-popover/feature-RC-21569-popover-left_2022-10-05-14-53.json
- packages/popover/src/Popover/__snapshots__/Popover.spec.js.snap
- packages/popover/src/PopoverContent/PopoverContent.js
Removes "left" position from PopoverGuide
BUG (Sort By Menu does not render under button chip due to left position being set to 0!important)
When 0!important is removed... it renders as expected!
> bug(RC-21569): removes left from PopoverGuide

- common/changes/pcln-carousel/fix-memory-leak_2022-09-28-18-34.json
- common/changes/pcln-design-system/fix-memory-leak_2022-09-27-17-29.json
- common/config/rush/pnpm-lock.yaml
- packages/carousel/package.json
- packages/core/package.json
- packages/core/src/Layout/Layout.tsx
Upgrading to the latest `moize` to get this fix: https://github.com/planttheidea/moize/pull/177
This PR also refactors `Layout` to no longer use `moize`.
> Fix serialization bug in Layout

- common/changes/pcln-design-system/resolve-typescript-complaint-ChipContentWrapper_2022-11-07-19-02.json
- packages/core/src/Badge/Badge.stories.tsx
- packages/core/src/Chip/ChipContentWrapper.tsx
* Changed the default story for Badge from `Default` to `_Badge` to match storybook pattern
* Created `IChipContentWrapper` interface
> fix ChipContentWrapper TS complaint

- common/changes/pcln-design-system/PPN-59016-update-link-and-textColorOn_2022-11-07-23-48.json
- packages/core/package.json
- packages/core/src/Divider/Divider.spec.tsx
- packages/core/src/Link/Link.spec.tsx
- packages/core/src/Link/Link.stories.args.ts
- packages/core/src/Link/Link.stories.tsx
- packages/core/src/Link/Link.tsx
- packages/core/src/__test__/mocks/colors.ts
- packages/core/src/utils/utils.spec.ts
- packages/core/src/utils/utils.ts
* `textColorOn` updated to include overrides for the light and dark colors, falling back to `text.lightest` and `text.base` as it was before. This allows us to set the fallback dark color to `primary` for example.
* Created `getValidPaletteColor` and `hasPaletteColorShade` as support functions
* `Link` disabled state added to support cards that can be disabled.
> Update link and textColorOn disabled states

- .github/workflows/continuous-integration.yml
- .github/workflows/npm-publish-beta.yaml
- .github/workflows/npm-publish.yaml
- .github/workflows/on-main.yml
Upgrading our workflows to run on Node 16 since 14 is deprecated.
> Update GHA workflows to run on Node 16

- common/changes/pcln-design-system/clickable-labels-and-storybook-improvements_2022-11-16-19-38.json
- packages/core/src/Label/Label.spec.tsx
- packages/core/src/Label/Label.stories.args.ts
- packages/core/src/Label/Label.stories.tsx
- packages/core/src/Label/Label.tsx
We use labels as clickable elements in a few place, I've seen people using custom styling so why not update it at the root.
I wonder if a `for` prop is passed in that the label should be `cursor: pointer` too 🤔 
While I was in the code, I updated some of the Label stories that made sense into the template format with controls.
> Clickable labels and storybook improvements

- packages/core/src/FormField/__snapshots__/FormField.spec.tsx.snap
- packages/core/src/Input/Input.stories.tsx
- packages/core/src/Input/Input.tsx
- packages/core/src/Input/__snapshots__/Input.spec.tsx.snap
Wrapping an Input component in a Label component would cause the Input text be the `text.light` color, matching the label and the placeholder text. I spoke to Wes and he said that this was not intended, so I have set the text color of an Input to always be `text.base`, @wesleymartin85 could you confirm this is the desired behaviour.
> Input text color should always be text.base

- common/changes/pcln-design-system/button-input-variation_2022-11-21-22-46.json
- packages/core/src/Button/Button.spec.tsx
- packages/core/src/Button/Button.stories.args.ts
- packages/core/src/Button/Button.tsx
Created a new variation for the `Button` component called `input` which makes the Button render in a similar fashion to an input. This is useful for situation like my screenshot when we want a dropdown, the clickable element to open the dropdown is a Button but it looks like an input.
> Button input variation

- common/changes/pcln-design-system/feat-add-border-for-swatch-component_2022-11-25-20-26.json
- packages/core/src/Swatch/Swatch.spec.tsx
- packages/core/src/Swatch/Swatch.stories.tsx
- packages/core/src/Swatch/Swatch.tsx
Added border (`border.base`). the Swatch color is `#FFFFFF` it is very difficult to see in light background.
> feat: Add border for Swatch component

- packages/core/README.md
This is a micro-cleanup of the README, mainly used to trigger a publish for the Design-System core package
> Remove broken badge in README

- apps/storybook/package.json
This PR enables Chromatic's [TurboSnap](https://www.chromatic.com/docs/turbosnap) feature to speed up Chromatic tests and reduce our monthly snapshot usage.
Example Storybook build step after changing `Button.tsx`: https://github.com/priceline/design-system/actions/runs/3875543293/jobs/6608225403#step:7:131
> Enable TurboSnap for Chromatic

- apps/docs/pages/utilities/getLinkStylesOn.md
- apps/docs/src/components.js
- apps/docs/src/navigation.js
- common/changes/pcln-design-system/feat-add-link-contrast-styling-helper_2023-01-11-22-53.json
- packages/core/src/Link/Link.stories.tsx
- packages/core/src/Text/Text.stories.tsx
- packages/core/src/index.ts
- packages/core/src/utils/utils.spec.ts
- packages/core/src/utils/utils.ts
v4 PR: https://github.com/priceline/design-system/pull/1241
- Similar to the `getTextColorOn` util but for links so that their default and on-hover state is accessible on different theme palette colors
- If not the default link color, add color, font weight, and underline styles
- Add new page to docs to demonstrate the three possible outcomes (light link, default link, and dark link styling)
- Add test suite for new util, also add some more coverage on other lines
- Add test command to core `package.json`
> feat(v5): Add util for getting link styles on color

- common/changes/pcln-icons/feat-HTL-86887-v4-sustainable-svg_2023-01-13-20-43.json
Ron's PR adding the Sustainability svg did not include a type change for the icons package: https://github.com/priceline/design-system/pull/1245/files#diff-ce82642d1194ef693b17c7c387e4fd3efcb3f8d18ecb5e68ad962a3e7a0123baR5
> Fix sustainability svg change for v4

- common/changes/pcln-design-system/checkbox-indeterminate-story_2023-01-23-15-27.json
- packages/core/src/Checkbox/Checkbox.spec.tsx
- packages/core/src/Checkbox/Checkbox.tsx
- packages/core/src/Checkbox/__snapshots__/Checkbox.spec.tsx.snap
The existing implementation of the `indeterminate` prop on `Checkbox` broke ref forwarding, which broke support for libraries like `react-hook-form`. This implementation is based on Material UI's implementation (see [here](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Checkbox/Checkbox.js#L182)) and uses React state rather than HTML attributes.
> Fix bug in Checkbox when using indeterminate prop

- common/changes/pcln-design-system/fix-getlinkstyleson-check-hover-color-contrast_2023-01-24-20-58.json
- packages/core/src/Link/Link.stories.tsx
- packages/core/src/utils/utils.spec.ts
- packages/core/src/utils/utils.ts
- In order to ensure contrast is maintained, we should also check the onhover color before we allow the default link styles to still apply
- Add condition for default contrast check and test for this case
- Update storybook with example as well
> fix(main): Check onhover color in getLinkStylesOn

- common/changes/pcln-design-system/fix-chip-filter-text-wrap_2023-02-16-15-44.json
- packages/core/src/Chip/ChipContentWrapper.tsx
- packages/core/src/Chip/ChoiceChip/ChoiceChip.stories.tsx
This change will prevent text inside `ChoiceChip` from wrapping. 
**Before:**
**After:**
> ChoiceChip text should not wrap

- common/changes/pcln-design-system/layout-spread-props-to-allow-overrides_2023-02-10-21-00.json
- packages/core/src/Layout/Layout.tsx
I need the ability to add margin to the top of a single row Layout, I could wrap with a Box component but this doesn't seem like a spec breaking thing and seems like it'd be valuable for others.
> Layout spread props to allow overrides

- common/changes/pcln-design-system/fix-two-prop-type-warnings_2023-02-28-19-18.json
- common/changes/pcln-menu/fix-two-prop-type-warnings_2023-02-28-19-18.json
- packages/core/src/FormField/FormField.spec.tsx
- packages/core/src/FormField/FormField.tsx
- packages/core/src/FormField/index.ts
- packages/core/src/Tooltip/Tooltip.stories.tsx
- packages/menu/src/Menu/Menu.js
* Update FormField to use an interface instead of prop types
* Pass id prop to Popover idx prop to fix prop type warning
We have a situation where the label for our FormField needs to be outside of the FormField but then a prop warning gets thrown. a11y is satisfied but we still get the warning. I'm removing the prop check as there are edge cases that make this check incorrect.
Here is the component in question:
https://user-images.githubusercontent.com/62619213/221957723-ebc5990d-8347-4376-8aaa-d88c39509ef8.mov
> Fix two prop type warnings

- common/changes/pcln-design-system/add-textStyles-to-label_2023-03-02-23-45.json
- packages/core/src/FormField/__snapshots__/FormField.spec.tsx.snap
- packages/core/src/Label/Label.tsx
- packages/core/src/Label/__snapshots__/Label.spec.tsx.snap
- packages/core/src/theme/__snapshots__/theme.spec.ts.snap
- packages/core/src/theme/theme.ts
- packages/core/src/utils/attrs/__snapshots__/typographyAttrs.spec.ts.snap
- packages/core/src/utils/attrs/typographyAttrs.ts
Wes explained to me that we need different label text styles for different situations. For example, a form checkbox vs filter checkboxes, they both use labels but they need to be styled differently. This is a perfect use case for textStyles, I just needed to add support for them to the Label component.
> Add the textStyle prop to the Label component

- tools/project-change-analyzer/src/getChangedProjects/getChangedProjects.ts
I think the issue is that we were comparing against the wrong branch when detecting changes. I also added a filter just to be safe.
> Fix bug in change analyzer when comparing against main

- packages/docs-utils/README.md
- packages/docs-utils/package.json
- rush.json
Resolves the following error when publishing:
> Rename docs-utils package to avoid NPM fees

- common/changes/pcln-icons/update-icon-package-peer-dependency_2023-04-10-19-54.json
- packages/icons/package.json
David brought to my attention in Slack that pcln-icons v5 is using pcln-design-system v4 as a peer dependency.
Seems like this was a mistake made when we merged v5 but someone correct me if I'm wrong.
> Update icon package peer dependency

- common/changes/pcln-design-system/replace-use-of-usetheme_2023-04-11-16-13.json
- common/changes/pcln-design-system/replace-use-of-usetheme_2023-04-11-16-55.json
- packages/carousel/package.json
- packages/core/package.json
- packages/core/src/ToastProvider/ToastProvider.tsx
- packages/docs-utils/package.json
- packages/menu/package.json
- packages/modal/package.json
- packages/popover/package.json
Using `useTheme` broke backward compatibility with Styled Components 4.
> Use withTheme instead of useTheme in ToastProvider

- common/changes/pcln-design-system/PPN-62379-create-toast-border-variation-and-fix-styles-being-overwritten_2023-04-24-18-10.json
- packages/core/src/Toast/Toast.spec.tsx
- packages/core/src/Toast/Toast.tsx
- packages/core/src/ToastProvider/ToastProvider.stories.tsx
- packages/core/src/ToastProvider/ToastProvider.tsx
- packages/core/src/__test__/mocks/toasts.tsx
Created a new border variation that just highlights the left border, this is a slightly cleaner looking Toast that suits the app I'm working on better. I also fixed the css being overwritten by adding `&&&` and set `pointer-events: none` to prevent the invisible absolute banner that positions the Toasts from affecting clicking behind it.
Storybook: https://5a85e56213417800200978ab-lxuugdthql.chromatic.com/?path=/story/core-toast--toast&args=variation:border
> Create Toast border variation and fix styles being overwritten

- common/changes/pcln-design-system/tweak-toast-border-variation-design_2023-04-25-16-12.json
- packages/core/src/Toast/Toast.spec.tsx
- packages/core/src/Toast/Toast.tsx
> Tweak toast border variation design

- common/changes/pcln-design-system/feature-add-subtle-type-link_2023-04-27-18-02.json
- packages/core/src/Button/Button.spec.tsx
- packages/core/src/Button/Button.tsx
- packages/core/src/Link/Link.stories.tsx
- packages/core/src/Link/Link.tsx
I'm currently working on this ticket https://priceline.atlassian.net/browse/SITE-20524. I've to use the `Link` with `subtle` type. Which is currently not available. This change will allow us to use it.
Also , there are changes to the `background-color` of hover state in Button. To match the specs in here https://www.figma.com/file/1lLCo0ZnO1RyMDEbnnS0by/Web-Design-System?type=design&node-id=145-21874&t=mqAZdqJ3WFQmYcB2-0 , for subtle, palin and white type
> Update Link and Button component with changes to hover state in subtle, plain and white

- common/changes/pcln-design-system/HTL-XXX-pass-color-props_2023-05-17-21-44.json
- packages/core/src/Chip/ButtonChip/ButtonChip.tsx
No color is showing on `focus` for ButtonChip. I'm passing props as outlined in the docs here https://priceline.github.io/design-system/utilities/getPaletteColor#palette-color-driven-from-other-prop
> feat(HTL-XXX): fix outline color

- common/changes/pcln-design-system/update-hero-image_2023-06-16-21-52.json
- packages/core/src/DocsUtils/Hero/Hero.stories.tsx
This PR changes the `src` url for the image that is used in the  `Hero` component's story. 
Q: Why?
A: The previous `url` would load a random image from [unsplash](https://source.unsplash.com/random/?superhero/), and the new url loads a static Priceline image asset. With a static asset, we can ensure that chromatic snapshots do no produce a visual diff just because a random image was loaded on every build.
> Update Hero story image

- common/changes/pcln-design-system/fix-hug-background-color-gap_2023-07-10-15-58.json
- packages/core/src/Hug/Hug.tsx
- packages/core/src/Hug/__snapshots__/Hug.spec.tsx.snap
- currently when a hug holds a card with a border radius, we see a gap in the corners
- updating the hug to have the same background color as the header, by passing `color` on the hug so it can be used in `applyVariations`
Before: 
After:
> update hug to use same background color as header

- common/changes/pcln-modal/HTL-90706-modal-corners_2023-07-06-14-53.json
- packages/modal/src/Modal.jsx
- packages/modal/src/ModalHeader.jsx
- packages/modal/src/__snapshots__/Headers.spec.js.snap
Draft PR to address the corners of the modal outlined here https://github.com/priceline/design-system/issues/1318
This PR, as an added bonus, would also fix the small modal header overflow
**Before**
**After**
> feat(HTL-90706): add borderRadius

- common/changes/pcln-design-system/uxpt-4952-update-toggle-states_2023-07-10-20-50.json
- packages/core/src/Toggle/Toggle.spec.tsx
- packages/core/src/Toggle/Toggle.stories.tsx
- packages/core/src/Toggle/Toggle.tsx
**Confirmed disabled states for both disabled on and off**
Disabled ON
Disabled OFF
**Added hover states when toggle is selected and enabled**
**Updated the focus to focus-visible for keyed events**
**Added boxShadowSize to handle (sm for off/on, xl for off/on hover)** 
xl for off/on hover
sm for off/on
> feat(uxpt-4952): updated the toggle states

- common/changes/pcln-design-system/fix-hug-color-scheme_2023-07-13-15-27.json
- packages/core/config/jest.config.json
- packages/core/src/Hug/Hug.spec.tsx
- packages/core/src/Hug/Hug.stories.tsx
- packages/core/src/Hug/Hug.styled.ts
- packages/core/src/Hug/Hug.tsx
- packages/core/src/theme/theme.ts
- packages/core/src/utils/createColorScheme.ts
- packages/core/src/utils/utils.ts
Updated requirements: Using `colorScheme` on `Hug` should not set the header color to the color scheme's foreground by default.
> Fix hug color scheme

- common/changes/pcln-design-system/UXPT-4812-add-styling-card-as-button_2023-07-17-18-35.json
- packages/core/src/Card/Card.spec.tsx
- packages/core/src/Card/Card.tsx
- packages/core/src/Card/__snapshots__/Card.spec.tsx.snap
Small PR to style the `Card` when given the prop `as='button'`
When `hovered`
> feat(UXPT-4813): style when card as button

- common/changes/pcln-design-system/main_2023-08-03-21-57.json
- packages/core/src/SlideBox/BottomArrows.tsx
- packages/core/src/SlideBox/SlideBox.spec.tsx
- packages/core/src/SlideBox/SlideBox.stories.tsx
- packages/core/src/SlideBox/SlideBox.tsx
Update the `arrowPosition` prop default value to "hide" to fix downstream issue with mobile carousel displaying arrows when they were not before
> SlideBox: set arrowPosition default to hide

- common/changes/pcln-design-system/border-styles-on-card_2023-08-03-22-11.json
- packages/core/src/Card/Card.stories.args.ts
- packages/core/src/Card/Card.tsx
- packages/core/src/Card/__snapshots__/Card.spec.tsx.snap
- packages/core/src/storybook/args/index.ts
Adding the `borderStyle` prop to the Card component because I need to use it for a component I'm working on and assumed others might be able to benefit from this too.
https://styled-system.com/api/#border
I was torn between adding this to Card or to Box and therefore everything would get the benefit of it too. I can go back and make this change if people prefer that approach.
> Add borderStyles to Card component

- common/changes/pcln-design-system/UXPT-4882--Dialog_2023-08-03-18-16.json
- common/changes/pcln-design-system/UXPT-4882--Dialog_2023-08-04-16-28.json
- common/config/rush/pnpm-lock.yaml
- packages/core/package.json
- packages/core/src/Dialog/Dialog.spec.tsx
- packages/core/src/Dialog/Dialog.stories.args.tsx
- packages/core/src/Dialog/Dialog.stories.tsx
- packages/core/src/Dialog/Dialog.styled.tsx
- packages/core/src/Dialog/Dialog.tsx
- packages/core/src/Dialog/index.ts
- packages/core/src/Grid/Grid.tsx
- packages/core/src/index.ts
- packages/core/src/storybook/args/index.ts
- packages/core/src/theme/theme.ts
- packages/core/src/utils/createColorScheme.ts
- rigs/component/profiles/react/config/jest.config.json
This PR adds the `Dialog` component to the Priceline Design System. This dialog is based off of the [Radix-UI dialog primitive](https://www.radix-ui.com/docs/primitives/components/dialog), and prescribes some logical defaults to make usability more convenient for the developer. Here is a video demo of the component in action:
https://github.com/priceline/design-system/assets/23641048/255b4ab2-3853-4e27-b946-31915eeaeaf3
Also, this adds the `neutralDarkOnLightest` color scheme to the overall design system
> add Dialog component

- common/changes/pcln-design-system/resolve-avatar-prop-type-issue_2023-08-22-17-15.json
- packages/core/src/Avatar/Avatar.tsx
I noticed I was getting a prop type issue using the latest version of the DS and I tracked the issue down to the Avatar component.
`oneOfType` should be `oneOf` as `colorSchemeNames` is a list of strings such as `['primary', 'secondary', ...]`
> Resolve avatar prop type issue

- common/changes/pcln-design-system/accordion-types-use-typescript_2023-08-23-16-54.json
- packages/core/src/Accordion/Accordion.stories.tsx
- packages/core/src/Accordion/Accordion.tsx
Found an issue with Accordion types while trying to use the latest version of the design system. Not sure if this is due to my typescript config in my app or if this would never work but I decided to fix it this way.
> Accordion types use typescript

- common/changes/pcln-design-system/feat-HTL-94282_2023-09-18-13-17.json
- packages/core/src/Spinner/Spinner.spec.tsx
- packages/core/src/Spinner/Spinner.stories.args.tsx
- packages/core/src/Spinner/Spinner.stories.tsx
- packages/core/src/Spinner/Spinner.tsx
useGradient and strokeWidth property was added to the component.
An svg was created to handle smooth gradient and stroke line cap property
> Feat(htl-94282): Add Gradient and StrokeWidth to Spinner

- common/changes/pcln-design-system/fix-readonly-regressions_2023-09-21-16-37.json
- packages/core/src/Button/Button.stories.tsx
- packages/core/src/FormField/__snapshots__/FormField.spec.tsx.snap
- packages/core/src/Input/Input.tsx
- packages/core/src/Input/__snapshots__/Input.spec.tsx.snap
- packages/core/src/RadioCheckToggleCard/__snapshots__/RadioCheckToggleCard.spec.tsx.snap
- packages/core/src/Toggle/Toggle.tsx
Bonus examples of properly styling a `Button` like an `Input` without being semantically incorrect and violating a11y rules.
> Fix regressions related to readonly in Input and Toggle

- common/changes/pcln-modal/bugfix-fix-modal-overflow_2023-09-25-16-21.json
- packages/modal/src/Modal.jsx
- packages/modal/src/Modal.stories.jsx
- Revert the `overflow-y: auto` change that was introduced in this [PR](https://github.com/priceline/design-system/pull/1319/files#diff-5b5f252abb56263bc4b86a7916c35586d4e9c96da30f35e18e66d1e9ed013eb2R57)
- The change was breaking the modals where form elements are hosted that naturally overflow the modal (when the elements are in an active state)
Broken state
Current Production state
> bugfix: Allows elements inside the Modal to overflow on the y axis

- common/changes/pcln-design-system/feat-accordion-headerDividerColor_2023-10-31-17-59.json
- packages/core/src/Accordion/Accordion.stories.tsx
- packages/core/src/Accordion/Accordion.styled.tsx
- packages/core/src/Accordion/Accordion.tsx
Add `headerDividerColor` prop to the `Accordion` component. This will take in a DS color that will add a border-top to each step in the `ladder` variation (except for index === 0)
`headerDividerColor === undefined`:
`headerDividerColor === 'border.base'`:
> Feat accordion header divider color

- common/changes/pcln-design-system/feature-update-chat-message-component_2023-11-11-16-40.json
- packages/core/src/ChatMessage/ChatMessage.stories.tsx
- packages/core/src/ChatMessage/ChatMessage.tsx
Allow `ChatMessage` accepts React Node as children.
> Make ChatMessage accept react node as children

- common/changes/pcln-design-system/bugFix-UXPT-4211-RemoveBgForDisableButtonLink1_2023-11-17-01-11.json
- packages/core/src/Button/Button.spec.tsx
- packages/core/src/Button/Button.tsx
Ticket : [UXPT-4211](https://priceline.atlassian.net/browse/UXPT-4211)
This PR is to fix the bg of link variant of button, when disabled.  As the bg of `link` button css is overwritten by `buttonStyles` css, adding !important to fix it.
> Bug fix/uxpt 4211 remove bg for disable button link1

- common/changes/pcln-design-system/export-palette-family-variation_2023-11-27-19-15.json
- packages/core/src/theme/theme.ts
Exporting a new type for the possible palette shades:
```
[
'lightest',
'light',
'tint',
'base',
'heading',
'tone',
'dark',
'shade',
'darkest',
]
```
> Export palette family variation

- common/changes/pcln-design-system/feature-SITE-21794_2023-12-06-14-54.json
- packages/core/src/ChatMessage/ChatMessage.stories.tsx
- packages/core/src/ChatMessage/ChatMessage.tsx
> feat(SITE-21794): fix the outgoing ChatMessage footer position issue

- common/changes/pcln-menu/chore-AIR-59161-FixAccessibilityMenu_2023-12-14-16-45.json
- packages/menu/src/Menu/Menu.jsx
This Pr is to fix the accessibility issue, user lose the focus on Menu after selecting a menu item. The focus goes to top of the body after selecting any menu item. This issues is caused because of the popover position. In order to fix it we are passing the `querySelectorPortal` prop from menu.
> (AIR-59161):fix for loosing focus of menu after selecting menuitem

- common/changes/pcln-carousel/bugfix-AIR-59977-carousel_2024-01-05-15-04.json
- packages/carousel/src/Carousel.jsx
- packages/carousel/src/Carousel.stories.jsx
This sends the currentSlide property to the SliceBox component, ensuring it automatically scrolls to the indicated slide. This functionality was already in place for the Desktop Carousel but was previously absent in the Mobile Carousel.
> AIR-59977 Passed missing currentSlide prop to SlideBox component in Carousel

- common/changes/pcln-design-system/SITE-22333_2024-01-16-20-31.json
- packages/core/src/Dialog/Dialog.stories.args.tsx
- packages/core/src/Dialog/Dialog.stories.tsx
- packages/core/src/Dialog/Dialog.styled.tsx
- packages/core/src/Dialog/Dialog.tsx
- packages/core/src/theme/theme.ts
Ticket: https://priceline.atlassian.net/browse/SITE-22333
As per the discussion from DS guild on Friday this PR adds an overflowX & overflowY Control to the dialog while also not losing functionality.  
I changed the overflow on one of the containers in devtools within NL to confirm the change that was needed. Screenshot here: 
Attached is the dialog without devtools changes using controls in storybook: DEFAULT
OverflowX & Y set to visible: 
One unintended addition of adding overflowX is that the scrollbar when overflowX="visible" is not rounded. 
Unfortunately with the DSV6 upgrade we will not be able to implement this change at this exact moment - but once Next-landing is migrated we will pick the effort back up.
> Add OverflowX & OverflowY Props to the dialog component

- common/changes/pcln-design-system/AIR-60631_2024-01-24-20-07.json
- packages/core/src/Accordion/Accordion.stories.tsx
- packages/core/src/Accordion/Accordion.styled.tsx
- packages/core/src/Accordion/Accordion.tsx
When card or flatCard variant  closed no changes are needed, when open both would have no shadow and use the border of 1px and color border.base.
> fix(AIR-60631): update accordion shadow state for open

- common/changes/pcln-design-system/toast-provider-top-animation_2024-02-07-21-23.json
- packages/core/src/Animate/Animate.tsx
- packages/core/src/ToastProvider/ToastProvider.spec.tsx
- packages/core/src/ToastProvider/ToastProvider.stories.tsx
- packages/core/src/ToastProvider/ToastProvider.tsx
- Update the `ToastProvider` to allow users to specify **top** or **bottom** positioning of the `Toast`. This will default to `bottom: 20` and `top: undefined`
- Update the `Animate` to add in 2 new options: **slideInTop** and **slideOutTop**
> ToastProvider: update to allow animations to come in from the top

- common/changes/pcln-design-system/dialog-header-updates_2024-02-15-15-24.json
- packages/core/config/jest.config.json
- packages/core/src/Dialog/Dialog.stories.tsx
- packages/core/src/Dialog/Dialog.styled.tsx
- packages/core/src/Dialog/Dialog.tsx
- packages/core/src/useScrollWithShadows/useScrollWithShadow.ts
- packages/core/src/useScrollWithShadows/useScrollWithShadows.stories.tsx
This PR adds an optional prop to put a shadow between the Dialog header and its content when the content overflows.
https://github.com/priceline/design-system/assets/3260642/d422452d-6d23-4a49-93e7-0088f0ad9a7c
> Create hook to apply shadow to a container on scroll

- common/changes/pcln-design-system/add-footer-content-to-dialog_2024-02-15-21-16.json
- packages/core/src/Dialog/Dialog.spec.tsx
- packages/core/src/Dialog/Dialog.stories.tsx
- packages/core/src/Dialog/Dialog.styled.tsx
- packages/core/src/Dialog/Dialog.tsx
Add footerContent section to the Dialog to support DatePicker, TravelerSelection and Typeahead mobile versions.
https://github.com/priceline/design-system/assets/62619213/da30d7f9-4a26-41d5-b074-c45ab086510b
> Dialog - Add footerContent section

- common/changes/pcln-carousel/feat-carousel-arrows-alignment_2024-02-20-19-41.json
- packages/carousel/src/Carousel.jsx
- packages/carousel/src/Carousel.spec.js
- packages/carousel/src/Carousel.stories.jsx
- packages/carousel/src/constants.js
Add 2 new props to the `Carousel`
**nodeBesideArrows**: Node that will display beside the arrows - will only display if arrows are top or bottom (with left or right alignment)
**arrowsAlignment**: String either "left", "right", or "center". Default to "center" only available if arrowsPosition is set to "bottom".
> Carousel: add in arrowsAlignment and nodeBesideArrows props

- common/changes/pcln-design-system/container-add-BoxProps-type_2024-02-27-19-38.json
- packages/core/src/Container/Container.tsx
Container type was missing the BoxProps union which is valid as Container extends Box functionality via styled-components.
> add BoxProps to Container type

- common/changes/pcln-design-system/UXPT-6348-fix-dialog-trapFocus_2024-02-07-20-15.json
- common/changes/pcln-menu/UXPT-6348-fix-dialog-trapFocus_2024-02-07-20-15.json
- common/changes/pcln-popover/UXPT-6348-fix-dialog-trapFocus_2024-02-07-20-15.json
- packages/core/src/Dialog/Dialog.stories.tsx
- packages/core/src/Tooltip/Tooltip.stories.tsx
- packages/menu/src/Menu/Menu.stories.jsx
- packages/popover/src/Popover/Popover.stories.jsx
Recently found issues with focus trap when placing a menu/popover in a Dialog component.
Created some simple stories to test focus trap for simple cases for a menu, popover, and tooltip inside a Dialog.
> [UXPT]: create stories for dialog use cases

- common/changes/pcln-carousel/fix-AIR-61584-carousel-test-id_2024-03-08-21-41.json
- packages/carousel/src/Carousel.jsx
- packages/carousel/src/Carousel.spec.js
- packages/carousel/src/RenderInView/RenderInView.jsx
The carouse would render the children twice, which caused the same children component with same test-id appear twice. 
Before fix
After fix
> fix(AIR-61584): avoid render the hidden children

- common/changes/pcln-popover/feat-RC-25645-disable-flip_2024-03-15-01-35.json
- common/changes/pcln-popover/feat-RC-25645-disable-flip_2024-03-15-13-31.json
- packages/popover/src/Popover/Popover.jsx
- packages/popover/src/Popover/Popover.stories.args.jsx
- packages/popover/src/Popover/Popover.stories.jsx
- packages/popover/src/usePopover/usePopover.js
By default the Popover component implements floating. I have a case where this is not desired. Rather than recreate the component without it I found that it is possible to disable the floating using `floating-ui` props:  `crossAxis` and `mainAxis`. 
When both of those are set to false no floating occurs. The component remains "sticky" to its original `placement`
I implemented this with a defaultProp that doesn't change the existing implementation. To disable it you must pass the new prop.
> feat(RC-25645): Disable floating-ui for popover using a prop.

- common/changes/pcln-menu/fix-RC-26177-menu-zindex_2024-04-16-14-30.json
- packages/menu/src/Menu/Menu.jsx
I am adding a prop for zindex for the pop up component inside menu. This is defaulted to 1600 the original value.
> fix(RC-26177): zindex prop for menu

- common/changes/pcln-menu/fix-HTL-103087-menu-scroll_2024-04-18-15-40.json
- packages/menu/src/Menu/Menu.stories.jsx
- packages/menu/src/MenuList/MenuList.jsx
Fixing a bug where opening the DS menu jumps to the top of the screen
https://github.com/priceline/design-system/assets/90357103/107b6817-9d99-4b0d-b6c0-b4945baca870
https://github.com/priceline/design-system/assets/90357103/771dee9a-923f-4bd5-9549-ad66f8f52459
> fix(HTL-103087): menu jumps to top of screen

- common/changes/pcln-design-system/rename-innerContentOverflow-prop_2024-04-29-21-42.json
- packages/core/src/Dialog/Dialog.styled.tsx
- packages/core/src/Dialog/Dialog.tsx
I need similar behaviour to what is being done with the `innerContentScroll` prop but I need to set the overflow to `hidden`. I don't want to create a whole new prop just to control this behaviour in a slightly different way so I thought renaming the prop and setting the changing the default value from `true` to `scroll` should help with backwards compatibility. This obviously isn't perfect, if anyone is setting this prop to false their code will be hurt by this but as this is the default functionality and a new prop anyway I think this is safe but I am happy to change the version bump if people disagree.
> Rename innerContentScroll prop to innerContentOverflow

- common/changes/pcln-popover/fix-UXPT-7566-toggleIsOpenOnClick_2024-07-09-14-11.json
- packages/popover/src/Popover/Popover.jsx
- packages/popover/src/Popover/Popover.spec.js
- packages/popover/src/Popover/Popover.stories.jsx
There is an issue for certain use-cases where we need to control the open/close state solely with prop changes. This prevents the click handler from automatically opening and closing the popover when `toggleIsOpenOnClick` is set to false. 
This logic is used to conditionally set the onClick handler based on the values of openOnHover, toggleIsOpenOnClick, and handleToggle. If the conditions are not met, it ensures that onClick is set to a no-op function (function() {}), preventing any potential errors from undefined or null references.
> fix(UXPT-7566): support programatic control of the popover

- common/changes/pcln-design-system/feat-UXPT-6345_2024-07-24-16-29.json
- packages/core/src/Dialog/Dialog.spec.tsx
- packages/core/src/Dialog/Dialog.stories.args.tsx
- packages/core/src/Dialog/Dialog.styled.tsx
- packages/core/src/Dialog/Dialog.tsx
**Desc:**
When I fixing a Penny chat bot accessibility issue, we couldn't swtich elemenets in chat bot modal by using 'tab' key.
After a long investigation, I found it's due to `tabindex='-1'` in `<Dialog/>` component. When I remove tabindex attribution from `<Dialog/>`, the accessibility issue is gone, we can swtich elemenets in chat bot modal by using 'tab' key. And I also found the `tabindex='-1'` in Dialog elemenet seems it's a default value. (Video recording of this issue https://app.screencastify.com/v3/watch/L7vnzLf7ZWQYuIibKmsh)
So I have two options to fix it,
Option 1 is to write a logic in penny chat bot, to get rid of tabindex from `<Dialog/>` when modal is rendered.
Option 2 is to update `<Dialog/>` component in pcln-design-system, to accept a new optional parameter, eg. …
> feat(UXPT-6345): add a new parameter 'shouldDisableTabIndex' to Dialog component

- common/changes/pcln-design-system/feat-UXPT-7739-replace-close-button-styling_2024-08-05-18-18.json
- packages/core/src/ChatHeader/ChatHeader.spec.tsx
- packages/core/src/ChatHeader/ChatHeader.stories.tsx
- packages/core/src/ChatHeader/ChatHeader.tsx
Minor modifications to the ChatHeader component:
1. The close button is now a CloseButton component
2. `onMinimize` is now optional and the `minimize` button will only be displayed if the `onMinimize` prop is passed.
Below is a comparison of old vs new. Old is on left, new is on right:
https://github.com/user-attachments/assets/4e8d2711-1fca-48ac-bcae-f00ab292a9f1
> feat(UXPT-7739): Leverage the CloseButton for the ChatHeader

- common/changes/pcln-design-system/fix-RC-25445-menuSSR_2024-08-12-15-53.json
- common/changes/pcln-menu/fix-RC-25445-menuSSR_2024-08-12-15-53.json
- common/changes/pcln-popover/fix-RC-25445-menuSSR_2024-08-12-16-20.json
- common/changes/pcln-popover/fix-RC-25445-menuSSR_2024-08-12-16-27.json
- packages/menu/src/Menu/Menu.jsx
- packages/menu/src/Menu/Menu.spec.js
- packages/popover/src/PopoverContent/PopoverContent.jsx
- packages/popover/src/PopoverContent/PopoverContent.spec.js
Update (9/4): This PR doesn't fix the original hydration issue but it resolves other potential bugs.
Apparently there is a [known issue](https://github.com/remix-run/remix/issues/4822) with React 18 where browser extensions will cause hydration issues. This makes sense because when we are developing alt-landing app locally we are using the Modheader chrome extension. Bumping to React 18 canary version/React 19 will solve browser extensions+hydration issue. 
I noticed a hydration issue with `CurrencySelector` in `@pcln/selectors` while trying to migrate alt-landing app (which is only used for Airport Rental Cars landing page) to use DS6+React 18. `@pcln/selectors > CurrencySelector` is used in `@pcln/white-label-components` > `Header`.
@sdalonzo pointed out there was a bug with pcln-menu …
> fix(RC-25445): use querySelectorPortal in pcln-menu and pcln-popover only when provided as a prop

- common/changes/pcln-design-system/feat-HTL-109459-multiroom-drawer_2024-10-22-16-20.json
- packages/core/src/Drawer/Drawer.stories.tsx
- packages/core/src/Drawer/Drawer.styled.tsx
- packages/core/src/Drawer/Drawer.tsx
Add zindex, modify padding, add prop to disable drag to dismiss animation
> feat(HTL-109459): multiroom drawer)

- common/changes/pcln-design-system/task-HTL-111885-scrolling-and-snapping-mechanism_2024-11-21-19-51.json
- packages/core/src/Drawer/Drawer.spec.tsx
- packages/core/src/Drawer/Drawer.stories.tsx
- packages/core/src/Drawer/Drawer.tsx
- packages/core/src/Drawer/helpers/getDividerStyle.spec.ts
- packages/core/src/Drawer/helpers/getDividerStyle.ts
- packages/core/src/Drawer/helpers/getDragToDismissAnimation.spec.ts
- packages/core/src/Drawer/helpers/getDragToDismissAnimation.ts
- packages/core/src/Drawer/helpers/getEnterAnimation.spec.ts
- packages/core/src/Drawer/helpers/getEnterAnimation.ts
- packages/core/src/Drawer/helpers/index.ts
- packages/core/src/Drawer/hooks/useSnap.spec.ts
- packages/core/src/Drawer/hooks/useSnap.ts
Changelog:
- The snap functionality works by changing the absolute positioning of a motion.div within a relative parent container. 
- On each drag action we update the position of the motion.div based on the percentage values we pass in as `snapHeights`. This prop accepts an array of 3 exact values `[top: string, middle: string, bottom: string]` as snap points.
- The extent of scroll and rigidity can be adjusted via `snapDimensions`, which controls the dimensions of the motion.div container.
Video 1: POC with div
https://github.com/user-attachments/assets/e4aa562a-3721-4d25-a833-f74e2d752fd5
Video 2: With Drawer
https://github.com/user-attachments/assets/e15739c8-6e37-4f0c-bb5b-de7c23a5095b
When resizing the viewport, it can trigger an enter animation based on a position change. Sometimes …
> Task/htl 111885 Drawer enhancements

- common/changes/pcln-design-system/bugfix-password-input_2024-11-13-19-16.json
- common/changes/pcln-icons/bugfix-password-input_2024-11-13-19-16.json
- packages/core/src/PasswordInput/PasswordInput.tsx
* visibility icon displaying password input is currently not working because the icon is not clickable
* verified fix in storybook
Main branch storybook with issue: https://main--5a85e56213417800200978ab.chromatic.com/?path=/docs/passwordinput--docs
Bugfix branch storybook: https://5a85e56213417800200978ab-fdhpatpceq.chromatic.com/?path=/docs/passwordinput--docs
> add z-index to icon button in password input in order to make it clickable

- common/changes/pcln-design-system/task-change-fragment-to-div-drawer_2024-11-27-20-07.json
- packages/core/src/Drawer/Drawer.tsx
`React.Fragment` throws type errors when invalid props are using it, changing to div fixes it.
> task(): Change fragement to div drawer

- common/changes/pcln-design-system/task-htl-112172-remove-old-conditional-prop-type-check_2024-12-17-20-59.json
- packages/core/src/Drawer/Drawer.tsx
Removing an old prop, follow-up to https://github.com/priceline/design-system/pull/1539
> task(HTL-112172): Remove old prop

- common/changes/pcln-design-system/task-htl-113265-duplicate-two-pointer-fix_2024-12-20-15-44.json
- packages/core/src/Drawer/hooks/useSnap.spec.ts
- packages/core/src/Drawer/hooks/useSnap.ts
**Problem:**
On mobile devices, touch scrolling can be misinterpreted as a drag action, potentially causing the Drawer container to respond incorrectly to the event.
See video for symptoms attached in previous PR, had to close due to a branch issue: https://github.com/priceline/design-system/pull/1541
**Solution:**
```
/**
* Differentiating between content scrolling and container dragging on mobile:
*
* 1. Content scrolling:
*    - Triggered by touch events
*    - Has a 'pointercancel' event type
*
* 2. Container dragging:
*    - Should not occur accidentally during content scrolling
*    - Has a 'pointerup' event type
*
* To prevent unintended container dragging, we only allow
* dragging when the event type is specifically 'pointerup'.
* This ensures smooth content scrolling without …
```
> task(HTL-113265): Pointer fix first commit

- common/changes/pcln-design-system/task-HTL-113523-abstract-out-ds-panel-states_2025-01-02-21-50.json
- packages/core/src/Drawer/Drawer.stories.tsx
- packages/core/src/Drawer/Drawer.tsx
- packages/core/src/Drawer/hooks/useSnap.spec.ts
- packages/core/src/Drawer/hooks/useSnap.ts
- packages/core/src/index.ts
Add listener to action on Drawer on snap events. 
The intent is to expose the previous and current snap states of the Drawer for the consumer application feature enablement (See unit test for example).
Simply put, client application can know the current and previous snap state is the drawer in, and can use it to conditionally render things.
**Snap position: TOP**
**Snap Position: MIDDLE**
**Snap Position: BOTTOM**
> task(HTL-113523): Expose drawer snap states

- common/changes/pcln-design-system/feature-PROT-4812-radio-toggle_2025-01-22-04-09.json
- packages/core/src/RadioCheckToggleCard/RadioCheckToggleCard.spec.tsx
- packages/core/src/RadioCheckToggleCard/RadioCheckToggleCard.stories.args.ts
- packages/core/src/RadioCheckToggleCard/RadioCheckToggleCard.stories.tsx
- packages/core/src/RadioCheckToggleCard/RadioCheckToggleCard.tsx
- packages/core/src/RadioCheckToggleCard/__snapshots__/RadioCheckToggleCard.spec.tsx.snap
- Adds optional backgroundColor prop to RadioCheckToggleCard component
- Updates title prop to string | React.ReactElement
- Adds new stories and unit tests
> feature(PROT-4812): adds backgroundColor prop to RadioCheckToggleCard

- common/changes/pcln-design-system/chore-UXPT-9083-Remove-Shimmer-DefaultProps_2025-02-03-14-15.json
- packages/core/src/Shimmer/Shimmer.tsx
Use of `DefaultProps` throws a warning in React 18.3, and an error in React 19. 
Removes the Shimmer component's DefaultProps
> chore(UXPT-9083): Remove Shimmer Component DefaultProps

- .all-contributorsrc
- common/changes/pcln-design-system/HTL-114826-accordion-dtls-rate-grid_2025-02-20-15-12.json
- common/changes/pcln-modal/HTL-114826-accordion-dtls-rate-grid_2025-02-20-15-12.json
- packages/core/src/Accordion/Accordion.spec.tsx
- packages/core/src/Accordion/Accordion.stories.tsx
- packages/core/src/Accordion/Accordion.styled.tsx
- packages/core/src/Accordion/Accordion.tsx
- packages/modal/src/__snapshots__/Headers.spec.js.snap
Bringing a previously approved PR back to life: https://github.com/priceline/design-system/pull/1537
- **Accordion**: Added useToggleText prop to allow customization of the toggle element. When set to true, the default arrow will be replaced with "More" and "Less" text
> feat(HTL-114826): add toggleText prop for accordion

- common/changes/pcln-design-system/fix-UXPT-9366-revert-attrs-changes_2025-04-07-20-25.json
- common/changes/pcln-slider/fix-UXPT-9366-revert-attrs-changes_2025-04-07-20-25.json
- packages/core/src/BackgroundImage/BackgroundImage.tsx
- packages/core/src/Badge/Badge.tsx
- packages/core/src/Badge/__snapshots__/Badge.spec.tsx.snap
- packages/core/src/BlockLink/__snapshots__/BlockLink.spec.tsx.snap
- packages/core/src/FormField/__snapshots__/FormField.spec.tsx.snap
- packages/core/src/Image/Image.tsx
- packages/core/src/Input/Input.tsx
- packages/core/src/Input/__snapshots__/Input.spec.tsx.snap
- packages/core/src/InputGroup/InputGroup.tsx
- packages/core/src/Label/Label.tsx
- packages/core/src/Link/Link.tsx
- packages/core/src/RatingBadge/RatingBadge.tsx
- packages/core/src/Select/Select.tsx
- packages/core/src/Stamp/Stamp.tsx
- packages/core/src/Stamp/__snapshots__/Stamp.spec.tsx.snap
- packages/core/src/ToggleBadge/ToggleBadge.tsx
- packages/core/src/ToggleBadge/__snapshots__/ToggleBadge.spec.tsx.snap
- packages/slider/src/RangeSlider.tsx
- packages/slider/src/Slider.tsx
We previously thought we correctly removed `defaultProps`, but for the handful of components using attrs it had unintended and confusing interactions which seems to have broken them. This is just an "emergency" revert to avoid any immediate issues, but we will have to find a working solution before a React 19 upgrade takes place.
> fix(UXPT-9366): revert defaultProps on attrs

- common/changes/pcln-modal/chore-UXPT-10092-Transition-Ref_2025-05-16-17-14.json
- packages/modal/src/Modal.jsx
The `Transition` component from `react-transition-group` fallbacks on React's deprecated `findDomNode` API if the `nodeRef` prop is not passed in. This breaks in `React 19` as it finally removed the API. The only component using Transition is in `@pcln/modal`.
- Added a `useRef` hook instance in `@pcln/modal` which is set to it's `Overlay` child component
- I was able to verify in Storybook that the modal animation functions **exactly** the same.
> chore(UXPT-10092): Update @pcln/modal to support React 19

- common/changes/pcln-icons/fix-UXPT-8374-svgs-r19_2025-05-28-02-46.json
- packages/icons/svgr.config.js
Unfortunately missed this the first round. A lot of our shared components rely on the individual svg components' default props.
Working in our first React 19 application, I noticed some of the SVGs are missing defaults
- Replaced some of the old deprecated React defaultProps for the generated SVG components
> fix(UXPT-8374): replace defaultProps in svgr template file

- .github/workflows/chromatic-ci.yaml
- .github/workflows/continuous-integration.yml
- .github/workflows/npm-publish-beta.yaml
- .github/workflows/npm-publish.yaml
- .github/workflows/on-main.yml
- .github/workflows/release-branch.yaml
- common/changes/pcln-design-system/chore-update-icons_2025-06-03-02-20.json
- common/changes/pcln-icons/chore-update-icons_2025-06-03-00-10.json
- packages/core/src/Banner/__snapshots__/Banner.spec.tsx.snap
- packages/core/src/Breadcrumbs/__snapshots__/Breadcrumbs.spec.tsx.snap
- packages/core/src/FloatingActionButton/__snapshots__/FloatingActionButton.spec.tsx.snap
- packages/core/src/FormField/__snapshots__/FormField.spec.tsx.snap
- packages/core/src/GenericBanner/__snapshots__/GenericBanner.spec.tsx.snap
- packages/core/src/Select/__snapshots__/Select.spec.tsx.snap
- packages/core/src/Step/__snapshots__/Step.spec.tsx.snap
- packages/core/src/Stepper/__snapshots__/Stepper.spec.tsx.snap
- packages/icons/package.json
- rush.json
- Update `styled-system` in `pcln-icons` to v5, to be in sync with all other `pcln-*` packages
- Move `styled-system` dependency as a dev and peer dep to `pcln-icons`. This is also in sync with all `pcln-*` packages
- Use Node.js v20 to build the packages
- Use the latest version of `actions/setup-node` GHA
- Update snapshots
> chore(): update pcln-icons to use styled-system v5 and use Node 20 for builds
